### ISSUE TITLE
Improve the validation of unknown fields in configuration objects

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1066]
a separate bug was discovered here when we found a typo in an etcd config field:
https://github.com/kubernetes/kubeadm/issues/1045
explanation here:
https://github.com/kubernetes/website/pull/9802#issuecomment-411905363

if `localEtcd` is passed instead of `local` the parsing fails silently and we don't get an error from the api-machinery code.

improve the validation for unknown fields.
adding this as a reminder here even if it belongs in another tracker.

@timothysc @bradfitz

**Comment by timothysc** [comment]
I'm ok with just a simple error message that makes it easy to grok.

**Comment by liztio** [comment]
sig-api-machinery is working on this:

kubernetes/kubernetes#67477
kubernetes/kubernetes#67594

unfortunately it looks like the PR to double-upstream (ghodss/yaml) got rejected, so they're not targeting v1.12 anymore.

I could write my own workaround, using `reflect` and a map, but we may just want to wait on k/k to merge the proper solution (especially since this is still alpha in v1.12)

**Comment by liztio** [comment]
@dims is trying again with ghodss/yaml#38, gonna call this blocked on that.

**Comment by timothysc** [comment]
We're going to have to punt this to 1.13 due to the dependency chain and 1.12 freeze.

**Comment by neolit123** [comment]
@bradfitz
kubeadm 1.13 has warnings that use a fork of https://github.com/ghodss/yaml + https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields as a backend.

**Comment by bradfitz** [comment]
@neolit123, great, thanks for the update!
