### ISSUE TITLE
remove the usage of the --allow-privileged flag in kubeadm

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1135]
Anything that relies on the kubelet's `--allow-privileged=true` flag will need to be replaced with a PodSecurityPolicy in future. So far I'm aware that this affects the guide to installing etcd with kubeadm but I'm guessing there are other docs this will affect. We will probably have to generate PSPs with kubeadm

This is important soon because `--allow-privileged` is probably going away in 1.13.

https://github.com/kubernetes/kubernetes/pull/53833#issuecomment-355399163
https://github.com/kubernetes/kubernetes/pull/57851

**Comment by neolit123** [comment]
i asked sig node a couple of times, about the roadmap for removing some other deprecated flags post the KubeletConfigtain changes and got no response.

while some of the flags do have a TODO:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go

i'm hoping that we are not hit by a surprise WRT to:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubelet/flags.go#L71
as we would need some time to think of a workaround.

**Comment by timothysc** [comment]
We just need to verify if this still exists.

**Comment by rosti** [comment]
Unmerged PR (sitting for months now) to delete kubelet's `--allow-privileged` controls is kubernetes/kubernetes#71835

If the basic idea of the PR stays the same we don't have to do anything, since kubeadm no longer supplies `--allow-privileged` to kubelet and removing the option from kubelet will preserve the current behavior.

Currently I don't think, that we need to setup any PSPs, but let's keep the issue opened until a PR for the final removal is merged (in case an action item emerges there).

**Comment by neolit123** [comment]
renamed the ticket to better explain the issue.

**Comment by neolit123** [comment]
reducing priority to backlog
PodSecurityPolicty is going away in the future replaced by new methods.

> This is important soon because --allow-privileged is probably going away in 1.13.

the flag is still recommended in 1.17.

**Comment by neolit123** [comment]
the PR moved to here https://github.com/kubernetes/kubernetes/pull/77820
and it merged May 2019.

closing the issue.
/close
