### ISSUE TITLE
certs renew all panics

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1190]
## Versions

v1.12.0 and master

## What happened?

run `sudo kubeadm alpha phase certs renew all --use-api=false` and then kubeadm panics

/kind bug
/priority critical-urgent
/area ux

**Comment by eliasp** [comment]
Is there a workaround to this?

**Comment by neolit123** [comment]
@eliasp 
i don't think so.

@liztio @fabriziopandini @timothysc 
given there is a panic in 1.12, arguably we need to backport a fix.

/priority critical-urgent

**Comment by eliasp** [comment]
When running `kubeadm alpha phase certs renew apiserver --use-api` I just get this:
```
failed to renew certificate apiserver: couldn't create certificate signing request: CertificateSigningRequest.certificates.k8s.io "kubeadm-certccpx4" is invalid: spec.request: Invalid value: []byte{0x30, 0x82, 0x3, 0x7, […REDACTED…], 0x2, 0xfa, 0xd8, 0x3b, 0x5d, 0x19}: PEM block type must be CERTIFICATE REQUEST
```

Is this related or worthy of another bugreport?

**Comment by neolit123** [comment]
@eliasp 
> Is this related or worthy of another bugreport?

yes, this is a separate issue.

on a quick look, we need to use this:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/cert/csr.go

instead of:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/renewal/certsapi.go#L73

otherwise the byte signature would fail here:
https://github.com/kubernetes/client-go/blob/master/util/certificate/csr/csr.go#L256

**Comment by timothysc** [comment]
I'll close for 1.13 now that the cherry-pick is up and approved.
