### ISSUE TITLE
Regression on Upgrade

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1224]
Kubedam v1.13 raise an error on the upgrade of clusters created with kubeadm v1.12.

The error happens when connecting to etcd, and this regression was introduced by stacked etcd change.

kubeadm v1.12 cluster are deployed with etcd listening on localhost only, while kubeadm v1.13 assumes etcd is listening both on localhost and on the advertising address.

I have a fix in flight, but we should also investigate why CI test on upgrades didn't provide a signal before

**Comment by neolit123** [comment]
seems that our upgrade tests `master-upgrade` have been failing for other reasons:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-upgrade-stable-master/2819/build-log.txt
```
I1109 08:15:48.277] [upgrade/config] FATAL: the ConfigMap "kubeadm-config" in the kube-system namespace used for getting configuration information was not found
I1109 08:15:48.277] [upgrade/config] In order to upgrade, a ConfigMap called "kubeadm-config" in the kube-system namespace must exist.
I1109 08:15:48.277] [upgrade/config] Without this information, 'kubeadm upgrade' won't know how to configure your upgraded cluster.
I1109 08:15:48.277] 
I1109 08:15:48.277] [upgrade/config] Next steps:
I1109 08:15:48.278]     - OPTION 1: Run 'kubeadm config upload from-flags' and specify the same CLI arguments you passed to 'kubeadm init' when you created your master.
I1109 08:15:48.278]     - OPTION 2: Run 'kubeadm config upload from-file' and specify the same config file you passed to 'kubeadm init' when you created your master.
I1109 08:15:48.278]     - OPTION 3: Pass a config file to 'kubeadm upgrade' using the --config flag.
```

i tried reproducing with k-a locally but failed, because k-a works for me only "sometimes".

also, i think i need to apply this patch to the older branches we support:
https://github.com/kubernetes/kubernetes/pull/68757/files

https://github.com/kubernetes/kubernetes/blob/release-1.12/test/e2e/framework/test_context.go#L236
https://github.com/kubernetes/kubernetes/blob/release-1.11/test/e2e/framework/test_context.go#L234

**Comment by AishSundar** [comment]
@nikopen @thanasisk as FYI

We should track it for 1.13 k8s cycle.

**Comment by nikopen** [comment]
as https://github.com/kubernetes/kubernetes/pull/70893 got merged, I assume this is now fixed. @neolit123 @fabriziopandini feel free to close if that's the case.
