### ISSUE TITLE
Consider having kubeadm version annotations for Pod objects

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1231]
as per the discussion here:
https://github.com/kubernetes/kubernetes/pull/70893#pullrequestreview-173625872

the alternative to Pod metadata is to have comments in manifest files, but these have to be parsed.

cc @fabriziopandini @luxas @rosti 
/kind design
/priority important-longterm

**Comment by neolit123** [comment]
/assign @timothysc @luxas @fabriziopandini 
WDYT
(proposed by @fabriziopandini [here](https://github.com/kubernetes/kubernetes/pull/70893#pullrequestreview-173625872))

**Comment by fabriziopandini** [comment]
+1
I think that making explicit that an object was created by kubeadm, tracking the last kubeadm version touched the object and when is a good think.
It add transparency to what kubeadm does and open ups to add  more robust version specific  logic

**Comment by NicolasT** [comment]
At first I was concerned this would imply the pods to be restarted because the manifest would always change. However, that's fine because when upgrading kubeadm-based deployments you'll always have at least some updates to field in the pod, like image version (maybe except for `etcd` if the preferred version and configuration doesn't change across kubeadm/K8s versions, which you may not want to restart without good cause?).

So, big :+1: (modulo `etcd`)

**Comment by neolit123** [comment]
seems a bit too late to change in this cycle, but IMHO a nice to have.
possibly early 1.15 we can get back to this.

**Comment by timothysc** [comment]
I debate if this has benefit in the future.

**Comment by astrieanna** [comment]
/remove-help

because it sounds as if there's some disagreement on whether this should be implemented.

**Comment by fabriziopandini** [comment]
/close
While i'm still convinced it is nice to have, currently there is no concrete use case for having those annotation. The ticket can always be re-opened/re-created if necessary

**Comment by neolit123** [comment]
SGTM. its a "nice-to-have safeguard" - viable if we reach another case where we have to mutate the manifests by knowning which version they were created with. hopefully not.
