### ISSUE TITLE
Cleanup external CA mode

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1258]
While testing v1.13 we discovered a regression in certs phases for sparse CA that was fixed by https://github.com/kubernetes/kubernetes/pull/71232

However, there is room for improving the current implementation as per comment https://github.com/kubernetes/kubernetes/pull/71232#pullrequestreview-176519779, but this requires a little bit of more thinking.

**Comment by fabriziopandini** [comment]
@seh 
https://github.com/kubernetes/kubernetes/pull/71232 merged, so now at head certificate management should support sparse certificates scenarios. Could you kindly give a feedback if all the cases are addressed?

**Comment by seh** [comment]
> Could you kindly give a feedback if all the cases are addressed?

It's working well for my case, which is probably unusual: I run in "external _etcd_ mode" and the faux "external front proxy mode," in that I create those keys and certificates myself and place them on the master machines; problems there were what motivated #807 and #918, both solved now.

I had been creating _all_ the certificates myself, avoiding the "certs" phase altogether. Now I'm taking advantage of _kubeadm init_'s improvements and allowing it to generate the API server certificates. Doing so allows me to run my master machines in an auto-scaling group, rather than creating each one as a "pet" with an accompanying network interface with a predetermined IP address (and hence a predetermined node name). Since I don't need to know the IP address ahead of time to create the API server certificate myself, I can let my cloud environment create the network interface, query the assigned IPv4 DNS name at boot time, feed that into _kubeadm init --node-name_, and let _kubeadm_'s "certs" phase use that node name in the API server certificate.

On that note, a diversion: I've noticed that [the _kubelet_ now logs a message periodically about overriding the cloud provider-supplied hostname](https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/pkg/kubelet/nodestatus/setters.go#L143-L145) with the hostname specified via the `--hostname-override` flag. That means that the _kubelet_ would probably get the right hostname (per kubernetes/kubernetes#64659, kubernetes/kubernetes#64661, and kubernetes/website#8873), but _kubeadm init_ needs that overridden hostname first, as it uses a more naïve way to determine a default node name. It seems like a chicken-and-egg problem; once the _kubelet_ is running with a cloud provider, it can figure out the right node name it should use, but before the _kubelet_ runs with a cloud provider, _kubeadm init_ has to choose a node name and then reconfigure the _kubelet_.

**Comment by fabriziopandini** [comment]
@seh good to know the certs part is working, so I'm closing the issue
/close

For the kubelet part eventually let's move the discussion to a separated issue, even if at first sight this is more a kubelet/cloud provider issue than a kubeadm issue.
