### ISSUE TITLE
Remove or fix dependency: difflib

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1368]
## Is this a BUG REPORT or FEATURE REQUEST?

/kind cleanup

## Versions
Any recent version

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
I found a dependency that I don't think we want: https://github.com/pmezard/go-difflib/ is used in the tests for output but the output is very misleading and the package is no longer maintained.

https://github.com/kubernetes/kubernetes/blob/8b98e802eddb9f478ff7d991a2f72f60c165388a/cmd/kubeadm/app/util/config/initconfiguration_test.go#L25

Here is example output:

```
            --- expected
            +++ actual
            @@ -115,7 +115,6 @@
               imagefs.available: 15%!
            (MISSING)   memory.available: 100Mi
               nodefs.available: 10%!
            (MISSING)-  nodefs.inodesFree: 5%!
            (MISSING) evictionPressureTransitionPeriod: 5m0s
             failSwapOn: true
             fileCheckFrequency: 20s
```

How would you interpret that?

<details>
<summary>answer is here!</summary>

`  nodefs.inodesFree: 5%!` is the only actual missing line.
</details>

## What you expected to happen?
I expect any dependency we take on to be maintained and if it's not there is a good reason. I suggest finding an alternative diffing library or removing the diff from the output entirely.

**Comment by neolit123** [comment]
aren't we using the same library in `upgrade diff`?

**Comment by chuckha** [comment]
we probably are. Perhaps we should consider adopting the unmaintained library into k8s?

**Comment by neolit123** [comment]
from what i've seen if we want to fork the library the process has to be stamped by sig-arc.

**Comment by neolit123** [comment]
@chuckha 
hm, i don't understand where the `MISSING` strings are coming from and what kind of diff format is that.
is this something you've added?

looking at the `-` on the `-  nodefs.inodesFree: 5%!` line i assume this line was removed.

here is how we use it in upgrades:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/upgrade/diff.go#L136-L141

related issue, that may be caused by bugs in this library?
https://github.com/kubernetes/kubeadm/issues/1015

**Comment by chuckha** [comment]
@neolit123 no, it's a go thing. My guess (and I haven't pinpointed it directly) is that there is a bug in difflib where if your diff contains a `%` then `fmt.Printf` at some point will think it needs to interpret that as a format and not a literal percent. Look at this: https://play.golang.org/p/iPCqoKTghav

**Comment by chuckha** [comment]
here is a minimal example to replicate:

```go
package main

import (
	"os"

	"github.com/pmezard/go-difflib/difflib"
)

func main() {
	ud := difflib.UnifiedDiff{
		A: []string{"5% hello world"},
		B: []string{"6% hello world"},
	}
	err := difflib.WriteUnifiedDiff(os.Stdout, ud)
	if err != nil {
		panic(err)
	}
}
```

output is:

```
--- 
+++ 
@@ -1 +1 @@
-5%!h(MISSING)ello world+6%!h(MISSING)ello world salazar:test cha$ 
```

**Comment by neolit123** [comment]
yep, that's definitely bug. given upstream is not maintained, we can:
A) look for an alternative library.
B) do a private fork (i'm OK with using my account) and propose to the k/k maintainers to update the vendor to point to a private repo.
C) fork the project under k-sigs. this needs politics.

we can go for A) right now, IMHO.

/assign @timothysc

**Comment by neolit123** [comment]
@chuckha

so there are a couple of problems here:

1) check https://github.com/kubernetes/kubernetes/pull/67709/files
this PR implements different defaults for linux vs non-linux in the kubelet.
and we need to handle that (possibly separate YAML per linux vs non-linux).

2) the example here: https://github.com/kubernetes/kubeadm/issues/1368#issuecomment-459366728
prints fine for me. but if i feed the result to `fmt.Printf` it fails. this is because the strings contains unescaped `%` and is it treated as format string. are you sure this exact example fails for you?

i tried breaking the difflib multiple times and it seems to work fine for windows and linux as long as you avoid the above scenario (`%` -> printf)

**Comment by neolit123** [comment]
actually let me create a separate issue for the unit tests.

**Comment by chuckha** [comment]
@neolit123 ah that exact example breaks with the version d8ed262 which is the version vendored by k/k:

https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json#L2968-L2969

**Comment by neolit123** [comment]
ok, understood.
i see the fix upstream here:
https://github.com/pmezard/go-difflib/commit/017ffa654c626b327474628673a99f0adb51e8c5

we should update that SHA to the latest version. asking what the policy about that is in #sig-release
