### ISSUE TITLE
Tracking issue for kubeadm integration with kustomize

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#1379]
## This a FEATURE REQUEST?

A number of feature requests we've had over time have all centered around the idea plumbing through options into what eventually becomes the end-state of a pile of YAML.  Some things make sense to expose as knobs, but other things don't.  

The purpose of this issue is to explore the option and impact of what is would mean to add a kustomize step @ certain phases of YAML generation.  

@neolit123 @fabriziopandini @luxas 

design proposal (tracking issue/KEP): https://github.com/kubernetes/enhancements/issues/1177

**Comment by luxas** [comment]
I'm not gonna have time to work on this quite yet, doing the other refactoring of the other components to use componentconfig first

**Comment by fabriziopandini** [comment]
This is indeed a good idea, even if currently the pile of yaml is super fragmented across the kubeadm code base, and not always managed consistently.

So it is important to decide since the beginning if we want kustomize applied selectively or if we should go for a deeper refactor: First generate all yamls, then kustomize, then apply to the cluster (kubeadm 2.0)

Another thing we should define is what kind of support is provided for Kustomized cluster (for join/upgrades)

**Comment by randomvariable** [comment]
This is also potentially part of #683 if CIS Docker Benchmarks are also considered.

**Comment by jfbai** [comment]
Is there any design proposal or PR for this feature request?

**Comment by fabriziopandini** [comment]
initial design proposal. https://docs.google.com/document/d/1SfZlCabOtu8BIzP_Q5sd5s8BhC75L8Wvz7aL-ce1Jhw/edit?usp=sharing
NB. this will be transformed in a KEP PR on k/enhancements in one or two days

**Comment by neolit123** [comment]
@fabriziopandini renamed the ticket and added kind/tracking issue.
please keep the OP updated with a list of PRs and TODO tasks.

**Comment by fabriziopandini** [comment]
done in 1.16
/close
