### ISSUE TITLE
Kubeadm: Allow overriding KubeletRunDirectory

### ISSUE THREAD

**Issue by ygalblum** [kubernetes/kubeadm#1478]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm, kubelet, root-dir

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

**What would I like to be added:**
Currently, the user can change kubelet's run-time directory by setting "root-dir" in the kubeletExtraArgs field of nodeRegistration object. While this flag does alter kubelet's behavior, kubeadm still writes the configuration files for kubelet under /var/lib/kubelet.

So, kubeadm should have its own parameter for the kubelet run-time directory to which it will write the configuration files. It can also pass the value of this parameter (if provided) to kubelet instead of using the kubeletExtraArgs map.

**Why is this needed:**
I'm running K8S on a VM with two volumes - a limited boot volume and a configurable (to be much larger) data volume. So, I'm trying to move run-time data from the boot volume to the data volume. I've already set docker and kubelet to use the data volume, and I would like to have kubeadm do the same

## Versions
All kubeadm versions on all environments

/kind feature

**Comment by yagonobre** [comment]
@ygalblum thanks for reporting this, I think it require changes on kubeadm config, and I'm not sure if we can add more changes to v1beta2.

/assign @rosti

**Comment by timothysc** [comment]
We've decide that we don't want to allow a root level override (e.g. chroot) for now. 

You could always solve this with a symlink today.

**Comment by Michael-Rinne** [comment]
@timothysc please reconsider your decision and reopen this issue.

We ran into the same issue, having a separate volume (/var/lib/docker) with large disk space and a very limited root volume.

We used a symbolic link before with K8s 1.7.11, but this started causing issues after upgrading to K8s 1.11.5, see issue [Pods stuck in Terminating status (UnmountVolume.TearDown failed) #65879](https://github.com/kubernetes/kubernetes/issues/65879) which is still open and according to a comment added 2 weeks ago still present in K8s 1.13.5.

Not being able to overwrite KubeletRunDirectory prevents us from applying the workaround for issue referenced above prior to executing "kubeadm init". Executing "kubeadm init" first, then patching file "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf", and re-starting kubelet service seems to be kind of dirty.

**Comment by Michael-Rinne** [comment]
Hi @yagonobre, sorry I don't get your query.

We have a separate volume mounted on `/var/lib/docker` and we do place kubelet root dir on that volume under `/var/lib/docker/kubelet`. We used to have a symbolic link `/var/lib/kubelet` pointing to `/var/lib/docker/kubelet`, but now we are running into the reference issue where K8s is unable to unmount volumes and this block new containers from starting up.

We tested successfully that modifying `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` where we update line:
```
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/docker/kubelet/config.yaml --root-dir=/var/lib/docker/kubelet"
```
solves the issue by not using a symbolic link as kubelet root dir.

However, we have an issue setting this up as kubeadm does not allow to override KubeletRunDirectory and then `kubeadm init` fails if we modified `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` before.

**Comment by ygalblum-stratoscale** [comment]
@Michael-Rinne 
For this specific issue you there are two ways you can pass parameters to kubelet before running kubeadm:
1. Using /etc/sysconfig/kubelet:
```
cat <<EOF > /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS=--root-dir=/var/lib/docker/kubelet
EOF
```
2. Via the kubeadm configuration file, by adding the section:
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta1
nodeRegistration:
  kubeletExtraArgs:
    root-dir: /var/lib/docker/kubelet

The problem is that in both cases, kubeadm will still create the director /var/lib/kubelet and save the configuration files it creates for kubelet in it

The solution that @timothysc suggested was to create a symbolic link for /var/lib/kubelet (which you did not do). So, that should fix your problem as well.

Having said that and even though this issue may be resolved using symbolic links, I think symbolic links should be used as a last resort or as an intermediate solution until the actual solution is in place. So, I would still like it if the feature request was given another look

**Comment by Michael-Rinne** [comment]
@timothysc, I am still trying to dodge the symbolic links issue in kubernetes [Pods stuck in Terminating status (UnmountVolume.TearDown failed) #65879 ](https://github.com/kubernetes/kubernetes/issues/65879).

I wrote a script which drives kubeadm using phases and moves files generated by kubeadm in `/var/lib/kubelet` to `/var/lib/docker/kubelet` as follows:

1. sed -i -e '...' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
2. kubeadm alpha phase certs all --config myKubeadmConfig.yaml
3. kubeadm alpha phase kubelet config write-to-disk --config myKubeadmConfig.yaml
4. kubeadm alpha phase kubelet write-env-file --config myKubeadmConfig.yaml
5. kubeadm alpha phase kubeconfig kubelet --config myKubeadmConfig.yaml
6. mkdir -p /var/lib/docker/kubelet
7. mv /var/lib/kubelet/config.yaml /var/lib/docker/kubelet
8. mv /var/lib/kubelet/kubeadm-flags.env /var/lib/docker/kubelet
9. systemctl daemon-reload
10. systemctl restart kubelet
11. kubeadm alpha phase etcd local --config myKubeadmConfig.yaml
12. kubeadm alpha phase kubeconfig all --config myKubeadmConfig.yaml
13. kubeadm alpha phase controlplane all --config myKubeadmConfig.yaml
14. kubeadm alpha phase mark-master --config myKubeadmConfig.yaml
15. kubectl apply -f kube-flannel-rbac.yaml
16. kubectl apply -f kube-flannel.yaml
17. kubeadm alpha phase bootstrap-token all --config myKubeadmConfig.yaml
18. kubeadm alpha phase upload-config --config myKubeadmConfig.yaml

The first `sed` command manipulates line for KUBELET_CONFIG_ARGS to become:
`Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/docker/kubelet/config.yaml --root-dir=/var/lib/docker/kubelet --cert-dir=/var/lib/docker/kubelet/pki"`

After this my cluster is up, as verified by `kubectl get nodes`:
```
NAME             STATUS    ROLES     AGE       VERSION
mcp-50-50-1-10   Ready     master    1h        v1.11.7
```
but the configmap "kubelet-config-1.11" is missing in namespace "kube-system" as verified by `kubectl -n kube-system get configmap`:
```
NAME                                 DATA      AGE
extension-apiserver-authentication   6         1h
kube-flannel-cfg                     2         1h
kubeadm-config                       1         1h
```
which is most likely caused by kubeadm not looking for kubelet config at `/var/lib/docker/kubelet/config.yaml`.

Having an option to override `KubeletRunDirectory` would make my life much easier and ensure that I do not hat to revisit this script again for next Kubernetes and kubeadm version (I am doing this for K8s 1.11 currently, because I need to support that version in production, but I have to do it as well for K8s 1.14 to support ongoing development).

@ygalblum-stratoscale, thanks for your feedback, I will test if your suggested kubeadm configuration file with `kubeletExtraArgs` under `nodeRegistration` helps, but I did not see it for kubeadm 1.11.7 when calling `kubeadm config print-default` which showed:
```
...
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: mvi-k8s-master
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
...
```

**Comment by Thinkwp** [comment]
You also can pass the following via `kubeadm join --config`:
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: $MASTER_IP:$PORT
    caCertHashes:
    - sha256:$CERT_HASH
    token: $TOKEN
nodeRegistration:
  kubeletExtraArgs:
    root-dir: $DATA_ROOT_DIR
```

**Comment by dbaumgarten** [comment]
I found a way to move the kubelet root-dir that seems to work fine with kubeadm.

- Set the new root-dir via kubeletExtraArgs in InitConfiguration and JoinConfiguration
- Create a symlink from /var/lib/kubelet to your new root-dir
- Run kubeadm as usual

This way kubeadm hits the symlink when writing the config-files and they end up in the right location.

The Kubelet does a lot of mount-juggeling inside it's root-dir. And that does not play well with symlinking (and for the record, also bind-mounting) /var/lib/kubelet somewhere else.
But if you do it this way, kubelet never encounteres the symlink (because root-dir is set properly) and kubeadm does not seem to have any issues with following the symlink.
