### ISSUE TITLE
post upgrade fails to backup apiserver certs

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubeadm#1498]
currently post-upgrades fail when kubeadm init is done cert-dir different from the default one `/etc/kubernetes/pki`. This is a common usecase (e.g. kubespray) to require a custom cert path.

This mostly due to relying on https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade.go#L157

currently the workaround is to symlink the default cert path with the custom one.

kubeadm version: 1.12

/assign
/priority important-soon

**Comment by fabriziopandini** [comment]
/kind bug
/area upgrade

@yastij thanks for the detailed report. 
If you would like to send a PR for fixing this problem, please set lifecycle active on the issue

**Comment by mattymo** [comment]
This issue looks like it's some misconfiguration. In most areas of kubeadm it uses this logic:
```
caCert, caKey, err := certsphase.LoadCertificateAuthority(cfg.cfg.CertificatesDir, caCertBaseName)
```

In app/phases/upgrade/postupgrade.go, it uses:
```
  certAndKeyDir := kubeadmapiv1beta1.DefaultCertificatesDir
```
That's just the default value, not the one actually set in the cfg object.

Since Kubespray backs up certs before upgrade and this error is not fatal, we can ignore it if rc=1 and this string is in the output. This file has been pointing to the default for over a year, but only in v1.14.0 it started throwing a fatal error, it seems.

**Comment by fabriziopandini** [comment]
@yastij 
fyi, there is work ongoing around certs renewal during upgrades that will touch API servers certs renewal. See https://github.com/kubernetes/kubernetes/pull/76862
