### ISSUE TITLE
Automatic update for version constants

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#1714]
Right now we have three Kubernetes version constants residing in [constants.go](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go). Those are `CurrentKubernetesVersion`, `MinimumControlPlaneVersion` and `MinimumKubeletVersion`.

These need to be bumped for every release cycle and this has already caused us issues in the past (see kubernetes/kubernetes#80834).

We already have the ability to generate a version during our bazel based build, thanks to some Git magic (see the kubeadm [version package](https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/version)). This package, however, may not be able to produce a version for builds of source tarballs and some other corner cases.

We need to find a way to generate the version constants, so that we won't need to do manual bumps. But at the same time enable easy development and testing workflow when the kubeadm version package does not provide us with a valid version.

/priority important-longterm
/area releasing
/help

**Comment by SataQiu** [comment]
We could probably use `kubeadm version package` to get version info for these constants.
```
import(
    pkgversion "k8s.io/kubernetes/cmd/kubeadm/app/version"
)

CurrentKubernetesVersion = version.MustParseSemantic(pkgversion.Get().String())
```

**Comment by neolit123** [comment]
> We already have the ability to generate a version during our bazel based build, thanks to some Git magic (see the kubeadm version package). This package, however, may not be able to produce a version for builds of source tarballs and some other corner cases

kubeadm should not be able to build without a build version, IMO.
i.e. the build should block if a tarball build does not feed a version.

> We could probably use kubeadm version package to get version info for these constants.

yes, if we can base these versions on the version of the binary it would be ideal.
but this way i don't think they will be constants any more.

instead of using constants we can have public getters that can have whatever logic necessary to return the proper versions for `CurrentKubernetesVersion, MinimumControlPlaneVersion and MinimumKubeletVersion`

**Comment by SataQiu** [comment]
Just have a try  kubernetes/kubernetes#81506
