### ISSUE TITLE
kubeadmin join cluster issue

### ISSUE THREAD

**Issue by houcong** [kubernetes/kubeadm#1846]
Envrionment is below:
CentOS： 7.6
Docker： 18.06.1-ce
Kubernetes： 1.13.4
Kuberadm： 1.13.4
Kuberlet： 1.13.4
Kuberctl： 1.13.4

I have already deployed a master node with 192.168.2.11 and then add another master node 192.168.2.13 to the cluster it goes wrong! Error is below

error creating local etcd static pod manifest file: etcdserver: re-configuration failed due to not enough started members

Anyone can help me

**Comment by houcong** [comment]
Whole page is :
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "k8s-master-03" as an annotation
I1021 17:31:18.098432   29097 join.go:566] [join] adding etcd
I1021 17:31:18.098446   29097 local.go:89] creating etcd client that connects to etcd pods
I1021 17:31:18.098451   29097 etcd.go:135] checking etcd manifest
I1021 17:31:18.103325   29097 etcd.go:182] etcd endpoints read from pods: https://192.168.2.11:2379,https://192.168.2.12:2379
I1021 17:31:18.112265   29097 etcd.go:223] etcd endpoints read from etcd: https://192.168.2.11:2379,https://192.168.2.12:2379
I1021 17:31:18.112285   29097 etcd.go:200] update etcd endpoints: https://192.168.2.11:2379,https://192.168.2.12:2379
I1021 17:31:18.112299   29097 local.go:98] Adding etcd member: https://192.168.2.13:2380
error creating local etcd static pod manifest file: etcdserver: re-configuration failed due to not enough started members

**Comment by neolit123** [comment]
/triage support
Is the etcd member on the primary node healthy?

**Comment by houcong** [comment]
Yes The etcd pod is ready status.
BTW the wrong one is my third node to add to the cluster the second is smoothly joined!

[root@k8s-master-01 etcd]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY   STATUS             RESTARTS   AGE     IP             NODE            NOMINATED NODE   READINESS GATES
coredns-78d4cf999f-5jp2b                1/1     Running            0          4h6m    10.20.0.7      k8s-master-01   <none>           <none>
coredns-78d4cf999f-qbxj5                1/1     Running            0          4h6m    10.20.0.6      k8s-master-01   <none>           <none>
etcd-k8s-master-01                      1/1     Running            0          4h5m    192.168.2.11   k8s-master-01   <none>           <none>
etcd-k8s-master-02                      1/1     Running            0          3h20m   192.168.2.12   k8s-master-02   <none>           <none>
kube-apiserver-k8s-master-01            1/1     Running            0          4h5m    192.168.2.11   k8s-master-01   <none>           <none>
kube-apiserver-k8s-master-02            1/1     Running            0          3h20m   192.168.2.12   k8s-master-02   <none>           <none>
kube-apiserver-k8s-master-03            0/1     CrashLoopBackOff   6          77m     192.168.2.13   k8s-master-03   <none>           <none>
kube-controller-manager-k8s-master-01   1/1     Running            1          4h5m    192.168.2.11   k8s-master-01   <none>           <none>
kube-controller-manager-k8s-master-02   1/1     Running            0          3h20m   192.168.2.12   k8s-master-02   <none>           <none>
kube-controller-manager-k8s-master-03   1/1     Running            0          19m     192.168.2.13   k8s-master-03   <none>           <none>
kube-flannel-ds-amd64-5vpr5             1/1     Running            0          3h45m   192.168.2.21   k8s-node-01     <none>           <none>
kube-flannel-ds-amd64-8fqxn             1/1     Running            0          3h20m   192.168.2.12   k8s-master-02   <none>           <none>
kube-flannel-ds-amd64-8lrqw             1/1     Running            0          3h44m   192.168.2.22   k8s-node-02     <none>           <none>
kube-flannel-ds-amd64-tlr8w             1/1     Running            0          4h3m    192.168.2.11   k8s-master-01   <none>           <none>
kube-flannel-ds-amd64-vm296             1/1     Running            4          77m     192.168.2.13   k8s-master-03   <none>           <none>
kube-proxy-47m8q                        1/1     Running            0          77m     192.168.2.13   k8s-master-03   <none>           <none>
kube-proxy-9zjpc                        1/1     Running            0          3h20m   192.168.2.12   k8s-master-02   <none>           <none>
kube-proxy-dr2jd                        1/1     Running            0          4h6m    192.168.2.11   k8s-master-01   <none>           <none>
kube-proxy-f2fqb                        1/1     Running            0          3h44m   192.168.2.22   k8s-node-02     <none>           <none>
kube-proxy-mf284                        1/1     Running            0          3h45m   192.168.2.21   k8s-node-01     <none>           <none>
kube-scheduler-k8s-master-01            1/1     Running            1          4h5m    192.168.2.11   k8s-master-01   <none>           <none>
kube-scheduler-k8s-master-02            1/1     Running            0          3h20m   192.168.2.12   k8s-master-02   <none>           <none>
kube-scheduler-k8s-master-03            1/1     Running            0          77m     192.168.2.13   k8s-master-03   <none>           <none>
kubernetes-dashboard-697f86d999-2pf86   1/1     Running            0          3h39m   10.20.2.2      k8s-node-01     <none>           <none>

**Comment by neolit123** [comment]
are the second and third nodes joined serially or in parallel?
we recommend serial, due to etcd issues.

**Comment by timothysc** [comment]
Please provide the exact steps you followed in order to reproduce this error.

**Comment by neolit123** [comment]
closing due to no response.

**Comment by zhaoguangqiang** [comment]
I have a problem like this.
My environment is VIP and 3 masters
I create the first master by a InitConfiguration.
Then i join the second/third master to cluster.
It can also successful join to the cluster after i reset the second master or third master.
But the first master cannot join to the cluster after i reset it.
The error message is "[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: etcdserver: re-configuration failed due to not enough started members
"
I feel confused.

**Comment by zhaoguangqiang** [comment]
> closing due to no response.
I have a problem like this.
My environment is VIP and 3 masters
I create the first master by a InitConfiguration.
Then i join the second/third master to cluster.
It can also successful join to the cluster after i reset the second master or third master.
But the first master cannot join to the cluster after i reset it.
The error message is "[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: etcdserver: re-configuration failed due to not enough started members
"
I feel confused.

**Comment by zhaoguangqiang** [comment]
@neolit123 
I have a problem like this.
My environment is VIP and 3 masters
I create the first master by a InitConfiguration.
Then i join the second/third master to cluster.
It can also successful join to the cluster after i reset the second master or third master.
But the first master cannot join to the cluster after i reset it.
The error message is "[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: etcdserver: re-configuration failed due to not enough started members
"
I feel confused.

**Comment by neolit123** [comment]
> error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: etcdserver: re-configuration failed due to not enough started members

when you reset the first master and try to re-join it, how many etcd members does the cluster have.
try downloading etcdctl and debug the problem (you need to learn how to use it).

using etcdctl you can inspect the health of the etcd cluster!

**Comment by zhaoguangqiang** [comment]
Yes, i try it by etcdctl and i found a unreachable etcd member with the VIP ip address . 
The first master can be re-join it after delete it from etcd cluster.
Thanks a lot! @neolit123
