### ISSUE TITLE
Pin version of kubernetes-anywhere to use for CI e2e job

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#191]
Our [CI kubeadm e2e job runner](https://github.com/kubernetes/test-infra/blob/master/images/ci-kubernetes-e2e-kubeadm/runner) does a `git clone` to fetch kubernetes-anywhere, which it uses to bring up a kubeadm-initialized cluster for testing. This makes the job fragile, since upstream changes to kubernetes-anywhere can inadvertently break our usage of it (see https://github.com/kubernetes/test-infra/pull/2093).

Before we start blocking PRs with runs of our e2e tests, we should really pin our runner to use a specific version of kubernetes-anywhere (via `godep`, or checking out a specific git commit, or otherwise) to avoid this. We can then occasionally refresh the version used to take advantage of new features or bug fixes, but explicitly test compatibility before pushing the update.

**Comment by luxas** [comment]
We should do this once kubernetes-anywhere is updated to use a kubeadm version that has https://github.com/kubernetes/kubernetes/pull/41417 merged. 

With that PR, kubeadm implements the desired behavior described in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bootstrap-discovery.md fir the first time.

After that PR one can also expect backwards-compability, because that's the last change that will merge before CLI stability for kubeadm init/join and token.

**Comment by luxas** [comment]
@pipejakob What's the status of this issue?
I _think_ I heard this was the case now, so this maybe can be closed...

**Comment by luxas** [comment]
friendly ping @pipejakob

**Comment by pipejakob** [comment]
It is currently functionally pinned because it's cloning my private fork of the repository (with custom fixes for our e2es). I've been working to get those fixes upstreamed, but when I ultimately flip back to using the real kubernetes-anywhere, I'll also add the commit pinning.
