### ISSUE TITLE
Self hosted pods should not mount host files

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes/kubeadm#194]
Right now the scheduler and the controller-manager consume files that live on the host. This binds them to a specific host. We should use `ConfigMap`s (`Secret`s?) instead.

**Comment by andrewrynhard** [comment]
@luxas is it safe to have a `ConfigMap` floating around with private keys for the scheduler and controller-manager?

**Comment by luxas** [comment]
@andrewrynhard I don't think either ConfigMaps or Secrets are _really_ safe as they are both stored in plaintext in etcd, but you're right, of those two `Secrets` are safer.

What's good on the other hand is that now with RBAC enabled, the scheduler and controller-manager client certs have unique credentials and are locked down in a way they can only do what they are supposed to, thus the attack surface is reduced with having these KubeConfig files as Secrets in the cluster.

But I think this would a good first step towards HA with self-hosting, to store the credentials cluster-wide with the right permissions set instead of on-disk on the master only.

@andrewrynhard Do you want to work on this?

**Comment by andrewrynhard** [comment]
@luxas I agree. This is definitely a good first step towards HA. I would like to work on this. I have already start messing around with it. I do think we might as well use `Secret`s. I believe I saw somewhere that there are plans to encrypt at rest too, but I could be wrong.

**Comment by luxas** [comment]
Yes, work is ongoing for encrypting them as well, but some releases away I'd guess.
You're now assigned officially assigned as well :)

**Comment by andrewrynhard** [comment]
Great! I will get started. Thanks.

**Comment by luxas** [comment]
Closing this as it's possible to self-host the certificates, but we won't enable this by default
