### ISSUE TITLE
kubeadm bundles outdated CNI plugins

### ISSUE THREAD

**Issue by weibeld** [kubernetes/kubeadm#1976]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.17.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.17.0
- **Cloud provider or hardware configuration**: GCP n1-standard-2
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS
- **Kernel** (e.g. `uname -a`): `5.0.0-1026-gcp #27~18.04.1-Ubuntu`
- **Others**:

## What happened?

Installed Kubernetes v1.17 with kubeadm v1.17. The default CNI plugins that kubeadm installs on the nodes are outdated and support only CNI spec 0.3.1 whereas the newest versions of these plugins most should support CNI spec 0.4.0. This may result in errors when a custom CNI plugin targeting CNI 0.4.0 calls one of these default CNI plugins and assumes that it also supports CNI 0.4.0.

For example, the currently included `host-local` plugin:

```
$ /opt/cni/bin/host-local <host-local.conf
{
    "code": 1,
    "msg": "incompatible CNI versions",
    "details": "config is \"0.4.0\", plugin supports [\"0.1.0\" \"0.2.0\" \"0.3.0\" \"0.3.1\"]"
}
```

Whereas the newest `host-local` plugin in the [containernetworking/plugins](https://github.com/containernetworking/plugins) repo supports 0.4.0.

See [containernetworking/plugins #425](https://github.com/containernetworking/plugins/issues/425#issuecomment-566023468).

It would be great if kubeadm could iclude the newest CNI package.

**Comment by neolit123** [comment]
not strictly a kubeadm issue, since kubeadm uses the following official k8s package:
https://github.com/kubernetes/release/blob/e29fdb0c249a44e9e1cc3f0507de65a770c8bf44/build/rpms/kubelet.spec#L29

so technically kubernetes packages outdated plugins.
looks like 0.8* added support for CNI 0.4.0, yet our PRs for updating to 0.8* are still on hold:
https://github.com/kubernetes/kubernetes/pull/78819
https://github.com/kubernetes/release/pull/731

please comment on these PR if you wish.
(also one for DEB has to be prepared).

thanks
