### ISSUE TITLE
`kubeadm token` commands should look in standard places for kubeconfig

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubeadm#198]
Currently the `kubeadm token` commands assumes it can find it's kubeconfig at `/etc/kubernetes/admin.conf`.  Instead, we should probably also look for the kubeconfig in the standard places and respect the standard env variables so that this can be used like `kubectl`.

Another option would be to move/duplicate the token management methods into `kubectl` directly as they can be managed off cluster.

**Comment by errordeveloper** [comment]
/remove-lifecycle stale

Assuming this didn't get fixed yet.

**Comment by neolit123** [comment]
hi, @liztio and @timothysc
i think i can help with this change-request.

just a little bit of clarification:

this would mean that we add more default search paths instead of just failing after no config is found in `/etc/kubernetes/admin.conf` and in case the user did not provide `--kubeconfig`?

apart from the paths listed in the `KUBECONFIG` env. variable, the current default path `/etc/kubernetes/admin.conf` and `~/.kube/config` are there any other paths to consider?

thanks

**Comment by neolit123** [comment]
send PR for review.
