### ISSUE TITLE
Can kubeadm accept a URL for manifest ?

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubeadm#2038]
Request for info:

Like kubelet watches a URL for static-pod manifests, can kubeadm configure API server to watch a URL for manifests?

**Comment by neolit123** [comment]
/triage support

static pod manifests are configured by kubeadm as a folder location, `/etc/kubernetes/manifests` because that is where kubeadm writes it's generated manifests files. so a local folder for generated manifests is required.

however you can also add extra static pods from URL:

e.g. 
```
...
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
staticPodURL: <some-url>
staticPodURLHeader:
  some-url:
  - some-header1
  - some-header2  
```

for more info on how to use KubeletConfiguration and the kubeadm configuration types see:
https://godoc.org/k8s.io/kubelet/config/v1beta1
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

/close
