### ISSUE TITLE
Increase robustness for kubeadm join TLS bootstrap

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#2091]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version**: kubeadm v1.17.*

## What happened?
While executing Cluster API tests, in some cases it was observed kubeadm join failures immediately after printing:
```
...
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
``` 
xref https://github.com/kubernetes-sigs/cluster-api/issues/2769

## What you expected to happen?
To make kubelet-start more resilient by:
1. increasing the TLS bootstrap timeout from to 2 or even 5 minutes (currently 40 sec?).
2. changing the code in order that also annotate CRI is retried as well.

## How to reproduce it (as minimally and precisely as possible)?
This error happens only sometimes, most probably when there is a temporary blackout of the load balancer that sits in front of the API servers (HA proxy reloading his configuration).

## Anything else we need to know?
Important: if possible the change should be kept as small and possible and backported

**Comment by rosti** [comment]
With my above message in light and with a proper clean environment (with kind) I figured out that the healthz check is not appropriate for us. In the kubelet that check is just a ping check (it will return 200 OK as long as the kubelet is running). Hence, it would return OK even if the kubelet is not bootstrapped yet.
However, due to the fact that `WaitForKubeletAndFunc` would return on any (not all) conditions, the healthz check is going to be executed after just 40 seconds and `WaitForKubeletAndFunc` would return without waiting for the bootstrap to be completed.

In my opinion we should stop using healthz while waiting for the bootstrap to finish and use only the existence of the bootstrapped kubelet.conf file (what `waitForTLSBootstrappedClient` does).

**Comment by neolit123** [comment]
> In my opinion we should stop using healthz while waiting for the bootstrap to finish and use only the existence of the bootstrapped kubelet.conf file (what waitForTLSBootstrappedClient does).

+1 waiting for the file to appear seems like a good indicator.
i don't think we have to validate the kubeconfig again, because we are doing that in the discovery part.

**Comment by fabriziopandini** [comment]
I'm not sure that getting read of WaitForKubeletAndFunc is the right thing to do.
As far as I understand, the current logics wait for the TLSBootstrapped, but if after some times the kubelet is not healthy, we exit fast.
So the healthz responding does not makes the wait loop to finish, but the healthz failing after a grace period of 40s yes
see also https://github.com/kubernetes/kubernetes/pull/89735#discussion_r401704557

**Comment by rosti** [comment]
You can see the current implementation [here](https://github.com/kubernetes/kubernetes/blob/8ae26096f7714b8ba95f62cf5018073dde2d1dfb/cmd/kubeadm/app/util/apiclient/wait.go#L159). Basically it waits for the first func (between `waitForTLSBootstrappedClient` and `WaitForHealthyKubelet`) to finish and then it returns.

With the current behavior of kubelet's healthz probe and in the case of slow API Server it's entirely possible that `WaitForHealthyKubelet` would exit first after a 40s wait, but before the bootstrap process is completed.

On the other hand, we can modify `WaitForKubeletAndFunc` to actually wait for both funcs to finish (instead of just one).

**Comment by rosti** [comment]
> @rosti, the `WaitForHealthyKubelet` triggers exit (returns to the channel) only in case of errors
> https://github.com/kubernetes/kubernetes/blob/8ae26096f7714b8ba95f62cf5018073dde2d1dfb/cmd/kubeadm/app/util/apiclient/wait.go#L163-L165

Sorry about that, I looked into the code again and it indeed was writing to the channel only upon an error. So you are right about it.

**Comment by fabriziopandini** [comment]
@rosti re-opening because we are still missing:
2. changing the code in order that also annotate CRI is retried as well.

/reopen

This basically means to get the following two calls moved in a separate func and wrapped in their retry statement :

https://github.com/rosti/kubernetes/blob/c1fc466cddfbbfa05403140662ce946dfca067db/cmd/kubeadm/app/cmd/phases/join/kubelet.go#L188-L197

IMO, a good initial setting for this operation is something like:
```
// An exponential backoff configuration that returns durations for a total time of ~40s.
// Example: 0, .5s, 1.2s, 2.3s, 4s, 6s, 10s, 16s, 24s, 37s
// Jitter is added as a random fraction of the duration multiplied by the jitter factor.
return wait.Backoff{
	Duration: 500 * time.Millisecond,
	Factor:   1.5,
	Steps:    10,
	Jitter:   0.4,
}
```

**Comment by fabriziopandini** [comment]
PS. Sorry if I missed this when reviewing kubernetes/kubernetes#89735

**Comment by rosti** [comment]
@fabriziopandini it's already retried using a polling timeout (see [here](https://github.com/kubernetes/kubernetes/blob/38f0a8bc74bed92bef87e20a79c36c5feea78b3d/cmd/kubeadm/app/util/apiclient/idempotency.go#L314)). It's currently at 500ms retry interval for a 2 minute timeout. It can receive the same treatment as above - bump the retry interval to 5s and the total timeout to 5 mins.

**Comment by fabriziopandini** [comment]
@rosti I think we are good for patch node (even if 500ms is somehow aggressive)
Instead ClientSetFromFile is not retried.
If this call is not affected by temporary connection problems, we are fine. Otherwise, this call should be retried as well

**Comment by neolit123** [comment]
@fabriziopandini @rosti 

did we:
- merge all required PRs for 1.19?
- backport for 1.18 and 1.17?

let me know how i can help.

**Comment by neolit123** [comment]
cherry picks:
https://github.com/kubernetes/kubernetes/pull/92117
https://github.com/kubernetes/kubernetes/pull/92116

**Comment by neolit123** [comment]
closing as cherry picks are LGTM/approved
/close
