### ISSUE TITLE
Add a test to check if all control-plane Pods use the "system-node-critical" priority class

### ISSUE THREAD

**Issue by prasadkatti** [kubernetes/kubeadm#2128]
Hi. I am looking to contribute with kubeadm tests. I came across the tests here - https://github.com/kubernetes/kubernetes/tree/master/test/e2e_kubeadm. So I was trying to see if there are any tests that I could add and I believe I have found some. But before I start working on it I wanted to check in here.

In 1.19 we have this new change `All static Pods use the system-node-critical priority class`. So I am planning to add tests to make sure that the priority class is properly added to the static pods.

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST
Addition of new tests.

## Anything else we need to know?
The test should only run for v1.19 and higher.

**Comment by neolit123** [comment]
it's not really needed but a nice to have, i guess.
so you can send it and see if someone disagrees on the PR.

our static pods are quite fixed in this regard and unlikely to change, after we moved to "node-critical".
our unit tests on the other hand guard potential drift in the source code.

SIG scheduling on the other hand already should have the test which is actually the important one - making sure that a high priority pod does not evict our static pods from a node.

**Comment by neolit123** [comment]
suggesting minor change in the name:
> All control-plane Pods use the "system-node-critical" priority class

**Comment by fabriziopandini** [comment]
I'm +1 to get this as a unit test (not as e2e/smoke test)

**Comment by prasadkatti** [comment]
Looks like the unit tests for [ComponentPod](https://github.com/kubernetes/kubernetes/blob/83a59c02f9b6fa29a352043509fca076c05bdb0e/cmd/kubeadm/app/util/staticpod/utils.go#L49) already test for the "system-node-critical" priority class.

**Comment by fabriziopandini** [comment]
Great! thanks for checking!
/close
