### ISSUE TITLE
Kubeadm HA control plane guide - haproxy timeout too short

### ISSUE THREAD

**Issue by camrossi** [kubernetes/kubeadm#2227]
Choose one: BUG REPORT

The configuration template for HAPROXY in https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#haproxy-configuration has the timers set to:

```
timeout client        20s
timeout server        20s
```

This, at least in my cluster will result in any KubeAPI call taking longer than 20s to fail. 
For example if I try to follow the logs I will get an error: unexpected EOF and the command will terminate after 20s.

```
kubectl   logs -f <POD> 
<SNIP>
error: unexpected EOF
```

We should probably changes these values to something higher like 300s perhaps. 
That is what I did in my cluster and it works fine now.

**Comment by neolit123** [comment]
/kind documentation
/area HA
cc @mbert do you think we should have these values higher.

**Comment by mbert** [comment]
I am not convinced that this problem is caused by wrong values for the timers. It looks like this is caused by the haproxy LB going round-robin. This is the normal behaviou that you get with NGINX as a load balancer, and obviously it's the same with haproxy. The workaround is configuring kubectl to talk to a control plane node rather than the virtual IP.

**Comment by camrossi** [comment]
For kubect no the connection is just reset by haproxy:

For example after setting the timers back to 20s:
`k8s-c1f1-01:~$ time kubectl -n guestbook  logs -f redis-master-7db7f6579f-l29bl
<--SNIP-->
[1] 22 Jul 01:17:57.308 * Synchronization with slave 10.102.0.159:6379 succeeded
error: unexpected EOF

real	0m20.121s
user	0m0.089s
sys	0m0.017s
`

If I set the timer back to 300s:

```
k8s-c1f1-01:~$ time kubectl -n guestbook  logs -f redis-master-7db7f6579f-l29bl
<--SNIP-->
[1] 22 Jul 01:17:57.308 * Synchronization with slave 10.102.0.159:6379 succeeded
error: unexpected EOF
error: unexpected EOF

real	5m0.115s
user	0m0.112s
sys	0m0.033s
```

So as you can see the times is what matters. Then if I re-issue the kubect command I will pick another master node. 

Even if have kubectl to it point to the real IP of a node I am wondering if there are other applications that can suffer from a 20s time out that are using the KubeAPI VIP. At minimum any application that waits for data now would have to have a TCP keepalive sent to the API VIP every 19s at least or have its connection terminated and potentially re-assigned to another node. 

I admit I do not know how all the possible KubeAPI calls should behave but 20s time out seemed a bit aggressive to me.

**Comment by mbert** [comment]
Thank you. I hope I find some time today to play through some scenarios on my test cluster. One thing definitely worthwhile trying would be running haprox with only one control plane node behind it and see how it behaves with the original timeouts.

If it turns out to be the timeouts then I'd even consider this good news because that would finally make the watch commands work with a load balanced set of control planes (which it didn't before). 

Whether or not to increase the timeouts anyway will IMO require some additional input from others. I do not have enough experience to give a recommendation here.

**Comment by mbert** [comment]
OK, I have looked into it. I could find no issues related to what I had written before. The behaviour I used to know from using NGINX as load balancer did not even occur anymore. That's good news.

Hence we're back to the original report. I don't know how to reproduce any API calls taking longer than 20 seconds. Increasing their values in the documentation seems fine to me, but which values should be used?

**Comment by camrossi** [comment]
I am also not really sure on what values we should use. 

I put 5minutes thinking that is plenty for a kubectl log -f use case and my cluster is happy now but is in a lab and I definitely don't have the experience required to give a recommendation for the whole community :)

**Comment by neolit123** [comment]
let's keep the default to 20 seconds and amend it if we see more reports of being insufficient in more setups.
thanks

**Comment by timgriffiths** [comment]
For future people with this same issue, I believe this is causing people issues as the read idle timeout of kubectl by default is 30 seconds  https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L145 so because we have haproxy setup to timeout after 20seconds it never gives the client a chance to send the keepalive ping to stop haproxy killing the connection. 

You can work around this on the client side by setting
```
export HTTP2_READ_IDLE_TIMEOUT_SECONDS=15
```
Or you can increase the timeout in haproxy to a number > 31 seconds
