### ISSUE TITLE
refactor cmd/kubeadm/app/preflight/checks_test.go

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2251]
unit tests should not execute system level code like port-checks and verifying existence of files outside of the control of specific test cases.

in here:
https://github.com/kubernetes/kubernetes/blob/4de8bdc6bcc86bc72ea1dfce5f134ac352f90a34/cmd/kubeadm/app/preflight/checks_test.go

we have TestRunInitNodeChecks and TestRunJoinNodeChecks that execute a number of hardcoded system checks:
https://github.com/kubernetes/kubernetes/blob/4de8bdc6bcc86bc72ea1dfce5f134ac352f90a34/cmd/kubeadm/app/preflight/checks.go#L876
https://github.com/kubernetes/kubernetes/blob/4de8bdc6bcc86bc72ea1dfce5f134ac352f90a34/cmd/kubeadm/app/preflight/checks.go#L953

the unit tests are problematic in cases where a port is occupied by e.g. a kube-scheduler on the same node and should not check for files that are in common hardcoded cluster locations.

what we should do instead is remove TestRunInitNodeChecks and TestRunJoinNodeChecks and break down individual checks/tests under TestRunChecks or under individual Test* functions, with the idea to preserve sufficient coverage.

some examples:
- PortOpenCheck can be unit tested with a fake server instance
- a FileAvailableCheck test can create a file under /tmp, make sure the path check returns error
- we shouldn't test FirewalldCheck unless we mock it to return values that we want
...

for more context about this see:
https://github.com/kubernetes/kubernetes/issues/93883#issuecomment-671929931
https://github.com/kubernetes/kubernetes/pull/93885#discussion_r468608208

**Comment by KofClubs** [comment]
@yashvardhan-kukreja Are you still working on this issue? I want to assign it to myself.

**Comment by yashvardhan-kukreja** [comment]
Sure, please move ahead. Thanks @KofClubs

**Comment by lunhuijie** [comment]
After learning the relevant information, I decided to do this.

**### Step 1: Add UT for checking file types**
Include：
  FileAvailableCheck
  FileContentCheck
  FileExistingCheck
  DirAvailableCheck

**### Step 2: Add UT for function that need a fake server**
Include：
  PortOpenCheck
  ServiceCheck

**### Step 3: Other checks analysis:**

_ExternalEtcdVersionCheck_ -- had done
_HTTPProxyCIDRCheck_ -- had done
_HTTPProxyCheck_ -- had done
_ImagePullCheck_ -- had done
_KubeletVersionCheck_ -- had done
_KubernetesVersionCheck_ -- had done
_MemCheck_ -- had done
_NumCPUCheck_ -- had done

_preflightCheckTest_ --needn't, because it is used only in checks_test.go
_SwapCheck_ -- needn't, because just cat /proc/swaps
_InPathCheck_ -- needn't, because all cases in TestRunChecks is enough
_ContainerRuntimeCheck_ -- needn't, because of simple logic
_healthCheck_ -- needn't, because of simple logic and diff package
_CoreDNSCheck_ -- needn't, because of simple logic and diff package
_IsPrivilegedUserCheck_ -- needn't, because it execute system level code
_SystemVerificationCheck_ -- needn't, because it execute system level code
_HostnameCheck_ -- needn't, because it execute system level code
_FirewalldCheck_ needn't, because it execute system level code

**### Step 4: Delete TestRunInitNodeChecks TestRunJoinNodeChecks**

PS：The above includes all checks. And the reason for not planning TestRunChecks is: the test here is mainly to test the logic of the RunChecks function. Even if it overlaps with other UTs, it is reasonable.

Do you have any other good suggestions for me?

**Comment by neolit123** [comment]
@lunhuijie thank you for looking at this.
the summary seems good to me. if you have a PR you can send it and we can try to review it.
