### ISSUE TITLE
upgrade plan with a version has stopped working on 1.19.0

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#2274]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
1.19.0

**Environment**:
- **Kubernetes version** (use `kubectl version`):
1.18.8
- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 20.04.01
- **Kernel** (e.g. `uname -a`):
Linux srv-ms9ld 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

The upgrade plan failed when you specify a version. 

```
$ sudo kubeadm upgrade plan 1.19.0
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.18.8
[upgrade/versions] kubeadm version: v1.19.0
[upgrade/versions] Latest stable version: 1.19.0
[upgrade/versions] Latest version in the v1.18 series: 1.19.0

[upgrade/versions] FATAL: configmaps "kubelet-config-1.19" not found
To see the stack trace of this error execute with --v=5 or higher
```

## What you expected to happen?

upgrade plan should work with a specified version as it does without a version. 
## How to reproduce it (as minimally and precisely as possible)?

As above. 

## Anything else we need to know?

upgrade plan without a version picks up the latest version in the 1.18 series correctly and generates a plan as expected.

**Comment by neolit123** [comment]
/assign @rosti

this seems to happen around:
> I0901 18:29:52.632452   10068 plan.go:88] [upgrade/plan] analysing component config version states
> [upgrade/versions] FATAL: configmaps "kubelet-config-1.19" not found

i think the problem is that it should just fetch the existing CM version instead of the one passed to plan?
this seems like a regression around the component config changes.

**Comment by rosti** [comment]
@neolit123 the problem here is the inconsistency of argument handling in the case of `upgrade plan`. We have a couple of different cases with respect to what `ClusterConfiguration` is returned by `enforceRequirements`:

1. If there is no argument, the returned `ClusterConfiguration.KubernetesVersion` is the old (currently installed) one
2. If there is an overwrite, the returned `ClusterConfiguration.KubernetesVersion` is the new (argument supplied) one

This bug was not exposed until now, because nobody was looking in `ClusterConfiguration.KubernetesVersion`. Luckily, the requirement to always supply a version to `upgrade apply` spares it from the same fate and `ClusterConfiguration.KubernetesVersion` always contains the version to upgrade to.

I'll try to make a more "cherry-pick-able" PR and then follow that with a more elaborate thing for 1.20.

**Comment by neolit123** [comment]
Thanks @rosti. Apparently the cherry pick deadline for 1.19.1 is this
Friday.
