### ISSUE TITLE
kubeadm should look for kubeconfig in pre-defined places

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/kubeadm#235]
**FEATURE REQUEST**

kubeadm should look for kubeconfig file in pre-defined locations and `kubeadm init` should copy admin.conf to one of these locations after cluster setup.

**DETAILS**

After creating a new cluster with kubeadm, one has to remember to follow these steps:

```
To start using your cluster, you need to run (as a regular user):

  sudo cp /etc/kubernetes/admin.conf $HOME/
  sudo chown $(id -u):$(id -g) $HOME/admin.conf
  export KUBECONFIG=$HOME/admin.conf
```
It's also necessary to ensure KUBECONFIG will be defined in the next login (or if the server is rebooted).

This extra step seems to be missed by some people (judging by feedback on GitHub issues and Slack), causing extra support work and impacting the experience for beginners.

Removing this step (while still making it possible to set KUBECONFIG and override this setting) seems like a good compromise.

**Comment by luxas** [comment]
This was fixed with: https://github.com/kubernetes/kubernetes/pull/44125

**Comment by jamiehannaford** [comment]
@luxas Should this be closed? Although kubernetes/kubernetes#44125 clarified some of the language in the docs, I think this issue is more about whether `kubeadm init` can just copy kubeconfig to a set location like `~/.kube/config`, so the user doesn't have to run anything after.

I also filed something similar recently https://github.com/kubernetes/kubeadm/issues/290.

**Comment by luxas** [comment]
@jamiehannaford I'm a bit (read: very) hesitant to/scared of adding functionality that just overwrites things you have globally in `.kube/config`.
Willing to have the discussion but...

**Comment by jamiehannaford** [comment]
@luxas Yeah it definitely needs thinking about. TBH my goal is just to reduce or minimize the amount of steps before a user can interact with their cluster. Another option could be saving kubeconfig to `~/.kube/kubeadm.conf` or something (with all the correct permissions), so we don't clobber any other configs and the user just needs to run `export KUBECONFIG=...`.

Maybe we can briefly bring it up in the SIG meeting tomorrow

**Comment by luxas** [comment]
@jamiehannaford Feel free to add it to the agenda

**Comment by luxas** [comment]
We covered this during the meeting and concluded that there is nothing more we can do here unfortunately.
The best we can do is to inform the user how to copy the kubeconfig file to `.kube/config` so that it always is available. This is what kubeadm prints out in v1.7:

```
mkdir -p $HOME/.kube
sudo cp -i {{.KubeConfigPath}} $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

We can't automate this as we don't know who the user is (since kubeadm is run as root)

**Comment by neolit123** [comment]
@luxas 

but if kubeadm is started with "sudo", you can get the regular user who started it.
from my experience starting "kubeadm init" from a root$ terminal didn't work, if i recall correctly.
...and this raises the question why should we allow root$ to start "kubeadm init", given the config needs a regular user?
