### ISSUE TITLE
kubeadm should allow using custom certificates

### ISSUE THREAD

**Issue by calvix** [kubernetes/kubeadm#239]
## FEATURE REQUEST

Hello,

`kubeadm` is managing certificate generation for you but this should be optional and not enforced.
In some cases you already have some service for certificate management (vault, AWS Certificate Manager ...) and you want issue certificate from that.

So the feature request is additional option which allow you specify path to your own certificates.

This could apply to both `kubeadm init` and `kubeadm join`.

**Comment by luxas** [comment]
You can generate whatever cert kubeadm would normally produce in beforehand and kubeadm will use it, so this works already.

We should probably document this better though...

**Comment by traustitj** [comment]
Is there any info on this anywhere ?

**Comment by hacktastic** [comment]
I would also like to know how this can be accomplished.

**Comment by luxas** [comment]
Whatever cert that exist and is valid will just be used by kubeadm instead of generated.
The most common use case will be: put your CA cert and key in `/etc/kubernetes/pki/ca.{crt,key` and kubeadm will use that CA to sign the rest of the certs.

More information here: https://github.com/kubernetes/kubeadm/pull/156

**Comment by calvix** [comment]
@luxas  But this means that i have to put `ca.key` on the filesystem? This does not seem very secure.

The main issue is that cert management is enforced by `kubeadm`, I would rather like to manage whole cert process by myself (meaning by some other service) and just give the `kubeadm` path to cert it should use.

**Comment by calvix** [comment]
I just read whole `phase` document, if i skip `cert` phase i should be able to  provide my own certs without need of providing `ca.key`

Questionis if there is some other step somewhere else which would break this. (maybe when running `kubeadm join` ?)

**Comment by vikashrepo** [comment]
@calvix @luxas 
How can I skip the kubeadm phase certs selfsign ? 
And are there any implications ?

**Comment by luxas** [comment]
You can generate all files kubeadm normally creates on beforehand and kubeadm will automatically skip the self-signing of the cert.

And yes, the ca.key has to exist on disk, the controller-manager is using/consuming it from there for TLS bootstrap signing of new node certs.

However if you want to make things more secure you can chain different CAs for different levels of trust...

**Comment by AlainRoy** [comment]
@luxas: I wonder if you can explain a bit further. I'm not sure if this is an architectural decision or a temporary limitation while kubeadm is being developed.

We would like to deploy Kubernetes in a way that is as standard as possible. My preference is to use kubeadm (I know it's not stable yet--that's okay, because it's getting there), but I want to provide all the certificates. My CA is a real CA--the CA operator will not give me the private key for signing certificates. 

I'm willing to generate all of the certificates and drop them into place. We have a secure mechanism for doing that with our CA. If I generate all the certificate and I provide a fake CA key, will kubeadm be happy? Or does kubeadm insist on having a real CA key that can be used to sign certificates? And if kubeadm does insist on this, is this an architectural choice, or is this a temporary situation while kubeadm is developed? 

Creating an intermediate CA is possible, but I've learned that running a CA that people trust is a tricky business, and I'd strongly prefer to never run a CA. 

Thanks!

**Comment by luxas** [comment]
@AlainRoy Requiring a valid/usable CA key is not a kubeadm limitation/requirement, it's a Kubernetes generic one. See https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-tls-bootstrap.md for an introduction to TLS bootstrapping which is heavily used in clusters.

However, why not try to get a Kubernetes-specific CA (with access to both cert and key) signed by your real/valid CA?

**Comment by AlainRoy** [comment]
I'm confused, but maybe I'm just not reading the proposal correctly. It looks like a CA key is not required, but is optional:

> When the kubelet executes it checks a location on disk for TLS assets (currently /var/run/kubernetes/kubelet.{key,crt} by default). If it finds them, it proceeds. If there are no TLS assets, the kubelet generates a keypair and self-signed certificate. We propose the following optional behavior...

Am I mis-reading it?

**Comment by mikedanese** [comment]
Kubernetes system component auth (for kubeadm and other deployment automation) is being developed around the certificates API. To use it, you need a functional certificates API. Alternatively you can opt out and roll your own.

Functional certificates API != CA keys stored on the master. All it means is that something is servicing certificate signing requests. This could be a shim between your CA and the kubernetes certificate API.

**Comment by AlainRoy** [comment]
Thanks, I've been doing some background reading based on your responses, and it's fitting together. I had some concerns about the idea of putting my CA private key on the Kubernetes master, but it's clear that we could implement an alternative CSR controller that would meet our security requirements. 

Thanks!

**Comment by mikedanese** [comment]
We do this in GKE if you want to take a look at the sample code:

https://github.com/kubernetes/kubernetes/tree/master/cmd/gke-certificates-controller

**Comment by AlainRoy** [comment]
Thanks @mikedanese, that's very helpful.

**Comment by jamiehannaford** [comment]
This now [documented](https://github.com/kubernetes/kubernetes.github.io/pull/4113), so we can close 🎉

**Comment by luxas** [comment]
Yayy :tada:
