### ISSUE TITLE
FR: provide a flag to choose CNI during kubeadm init

### ISSUE THREAD

**Issue by medyagh** [kubernetes/kubeadm#2408]
not sure if this should be a kubelet issue or kubeadm, please advice I will move to the right repo,
based on this comment 
https://github.com/kubernetes/minikube/issues/10788#issuecomment-797289498

in minikube we noticed that during kubeadm init, kuberentes picks up the first alphabetical CNI that could cause some unexpected issues. 

```
If there are multiple CNI configuration files in the directory, the kubelet
uses the configuration file that comes first by name in lexicographic order.
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni
```

would it be possible to have a flag to pass to kubeadm init to specify the CNI explicitly ?

**Comment by neolit123** [comment]
@medyagh kubeadm allows the users to configure the kubelet via KubeletConfiguration.
AFAIK the field to control this CNI related behavior is missing there, so that is a kubelet issue.

you can log a ticket for this in k/k and ping me on it, but it's for `/sig node` and `/area kubelet`.

thanks
/close
