### ISSUE TITLE
Support custom images for k8s components

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubeadm#2411]
Sometimes users want to compile k8s components and build customized k8s component images, push them to a private 
 repository. When installing k8s with kubedm, customized k8s image tags need to be specified, so this may be a good feature to support custom images for k8s components. 

Sometimes, we also use _Cluster API_ to create k8s cluster.

related to: https://github.com/kubernetes/kubernetes/issues/100174

---
edit neolit123

kubeadm v1beta2 link:
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

**Comment by fabriziopandini** [comment]
As per discussion in yesterday's office hours, this could be trickier than expected, because by allowing user to set image tags then we are compromising kubeadm capability to upgrade such images (*)
FYI many companies are solving a similar problem by having images tags equal to kubernetes version, where this could include metadata about the internal build; this has several advantages:
- it allows to upgrade components by simply changing a Kubernetes version
- it reduce the probability of errors/misconfigurations (only one value to set vs many)
- it makes explicit and easily discoverable the relation between the Kubernetes version in use and the image in use

(*) this is already happening for CoreDNS and Etcd, but those are external components and they follow different lifecycles that Kubernetes/Kubernetes components.
