### ISSUE TITLE
Add a validity period or expiration flag to `kubeadm alpha kubeconfig user`

### ISSUE THREAD

**Issue by dseomn** [kubernetes/kubeadm#2432]
## What keywords did you search in kubeadm issues before filing this one?

* kubeconfig expiration
* kubeconfig expire
* kubeconfig lifetime 

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Would it be possible to get a new flag to `kubeadm alpha kubeconfig user` to specify the expiration date (ideally as an offset from the current time) for the new client certificate? I'd like to be able to easily generate client certificates with lifetimes somewhere between ~5 minutes and ~1 day to avoid leaving long-term secrets on client computers. Maybe something like this?

```
kubeadm alpha kubeconfig user --lifetime=1h
```

## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:08:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux bullseye/sid
- **Kernel** (e.g. `uname -a`): `Linux k8sc0n0 5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux`

**Comment by neolit123** [comment]
note the command is moving / graduating to `kubeadm kubeconfig user` in 1.21 and will be removed from `alpha` in 1.22.

we have seen this request a few times in the past and it has rejected due to the potential of allowing users to sign credentials for very long periods of time.

but i can see the use case of producing short lived credentials using the `user` command.
i think a good compromise would be to add a flag called `--validity-period` and produce a klog.Warning if the user specifies periods longer than 365d.
365d should be the default value.

> --lifetime=1h

i'd prefer if we use a flag name that doesn't have "life" in the name, thus recommending `--validity-period` here.

to allow this, this function must be reworked to allow passing a value:
https://github.com/kubernetes/kubernetes/blob/5ad79eae2dcbf33df3b35c48ec993d30fbda46dd/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L281-L308

then the kubeadm PKI utils must also be aware of such a value:
https://github.com/kubernetes/kubernetes/blob/5ad79eae2dcbf33df3b35c48ec993d30fbda46dd/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L634

and not use this constant:
https://github.com/kubernetes/kubernetes/blob/5ad79eae2dcbf33df3b35c48ec993d30fbda46dd/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L659

note: the kubeadm configuration API or other commands **must not** allow a certificate period to be configurable.

PRs welcome.
