### ISSUE TITLE
kubeadm init pull "k8s.gcr.io/coredns/coredns:v1.8.0" in v1.21.1

### ISSUE THREAD

**Issue by AlohaPoster** [kubernetes/kubeadm#2475]
I use the "kubeadm init" and got this in v1.21.1:

[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns/coredns:v1.8.0: 

when i tag the same image to this name by "docker tag k8s.gcr.io/coredns:v1.8.0 k8s.gcr.io.coredns/coredns/v1.8.0" 
I got
"k8s.gcr.io/coredns/coredns/:v1.8.0" is not valid repository/tag : invalid reference format
should the "kubeadm init" pull "k8s.gcr.io/coredns:v1.8.0" but not "coredns/coredns:v1.8.0" ?

**Comment by neolit123** [comment]
in 1.21 the path to the coredns image was changed by the coredns team; also the tag now has a `v` prefix.
https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/kubeadm/app/constants/constants.go#L331-L334

this is now the valid path:
```
k8s.gcr.io/coredns/coredns:v1.8.0
```

> should the "kubeadm init" pull "k8s.gcr.io/coredns:v1.8.0" but not "coredns/coredns:v1.8.0" ?

`kubeadm init` pulls `k8s.gcr.io/coredns/coredns:v1.8.0`

> "k8s.gcr.io/coredns/coredns/:v1.8.0" is not valid repository/tag : invalid reference format

should be `k8s.gcr.io.coredns/coredns:v1.8.0`
but instead of using docker tag you can create a sub-path `/coredns/...` in your private image repository.

/kind support

**Comment by AlohaPoster** [comment]
Thanks a lot , cause of I'm nor familier with docker tag rule
