### ISSUE TITLE
How to change image path of coredns

### ISSUE THREAD

**Issue by UncleYi2016** [kubernetes/kubeadm#2501]
When I use my yaml config file to kubeadm init, it always show that I need to download coredns/coredns:v1.8.0 image. 
As default, it was set as  ``k8s.gcr.io/coredns/coredns:v1.8.0``, but I wanna use another image repository like ``registry.aliyuncs.com/google_containers``.
When I change the image repository, the image of coredns will be ``registry.aliyuncs.com/google_containers/coredns/coredns:v1.8.0``. But I want to change it into ``registry.aliyuncs.com/google_containers/coredns:1.8.0``. How can I change this configuration?
Thanks.

**Comment by fabriziopandini** [comment]
@UncleYi2016 the fact there we are adding coredns/coredns for a custom repository is a regression that affects v1.21.0 and v1.21.1; the problem has been fixed by https://github.com/kubernetes/kubernetes/pull/102502 and the change has been already back ported to the v1.21 branch and the fix will ship in v1.21.2
