### ISSUE TITLE
Support for MacOS?

### ISSUE THREAD

**Issue by jaylinnyc** [kubernetes/kubeadm#2504]
## Is this a request for help?

Yes, I have searched whole day online and couldn't find any help for support with MacOS.

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

kubeadm macos

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by neolit123** [comment]
hi. no there are no plan to support MacOS, because kubeadm and the component it deploys such as kube-proxy simply would not run on MacOS.

Windows support took years, so if MacOS users would like to outline all the changes that are required to k8s components this would definitely need a KEP and likely discussions with multiple k8s groups (SIGS):
https://github.com/kubernetes/enhancements/blob/master/keps/README.md

closing for the time being.

**Comment by jaylinnyc** [comment]
Thank you for the clarification.   Really appreciate it.
