### ISSUE TITLE
Kubeadm broken on armv6l

### ISSUE THREAD

**Issue by mitchhh22** [kubernetes/kubeadm#253]
I tried to install kubeadm on my raspberry pi zero W, but get an "Illegal Instruction"
On a raspberry pi 3 (armv7) it works just fine.

**Comment by clabu** [comment]
I am facing the same issue with a Raspberry Pi Model B+, also armv6.
```
$ kubelet --help
Illegal instruction

$ uname -a
Linux pi1 4.4.50-hypriotos+ #2 PREEMPT Sun Mar 19 14:44:01 UTC 2017 armv6l GNU/Linux
```

**Comment by clabu** [comment]
I downgraded to kubeadm 1.5.6 and it works. 1.6.0 gives the same error as 1.6.1.

**Comment by mitchhh22** [comment]
@clabu yeah downgrading to 1.5.6 works but can't join a 1.6+ cluster.

**Comment by luxas** [comment]
This is a known issue; it was discussed in https://github.com/kubernetes/kubernetes/issues/38067 and we dropped armel support (which part of RPi 1 uses when cross-compiling).

Basically armhf (GOARM=7) can't run on the Pi 1, so we used armel with GOARM=6 in -v1.5 to support RPi 1. However, we went all armhf in v1.6, hence it's not working on the Pi 1.

> Deprecate armel and use armhf images instead and use GOARM=7 instead of GOARM=6
> Motivation:
> - The only GOARM=6 board Go will support in go1.8 is the Raspberry Pi 1 which is just too slow to run newer Kubernetes versions.
> - Small performance improvements when using GOARM=7
> - The armel (http://hub.docker.com/u/armel) images are not updated as often as the armhf (http://hub.docker.com/u/armhf) images are.

For example, https://hub.docker.com/r/armel/debian/ was updated 8 months ago which is really bad from a security standpoint, vs https://hub.docker.com/r/armhf/debian/ which was updated 3 days ago.

Also, with the armhf switch, we were able to use https://hub.docker.com/r/armhf/alpine, which is great.

Hope it helps, but sorry for not being able to support the RPi 1 anymore.

If you want to help with documenting it/spreading the word, please do or come with suggestions

**Comment by wsargent** [comment]
I'm having this same problem on a Pi Zero

```
Linux p1 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux
```

**Comment by mthkunze** [comment]
Is it possible to discuses a reintegration of armv6l Support. I found many Posts showing the interest for using Kubernetes on Pi Zero and other armv6l Pi Devices. P Zero is good for hosting Micro Services in Kubernetes or Swarm Cluster Environments. Docker Swarm works well for me. So it would be nice if anyone could recycle the discussion. Pi clusterhat is properly a nice demo infrastructure.

**Comment by kfox1111** [comment]
Looking at the current docker.io build for the pi zero,
Go version: go1.9.3
and docker version: 18.02.0-ce

It does seem to be using a recent version of go.

I agree that there is not enough ram to use k8s on it in a standalone mode, but having it be a slave on a bigger master, it should have enough resources to do some useful things still.

**Comment by juliancheal** [comment]
Does anyone know if it's possible just to build from source to use my pi zeros as k8s nodes?

**Comment by svenwoldt** [comment]
would also love to know if kubernetes could use a pi zero as a worker node running one pod on it max plus log shipping potentially. The specs of the zero seem fine to use a bunch of them as a dedicated sensor cloud

**Comment by wxdao** [comment]
> For example, https://hub.docker.com/r/armel/debian/ was updated 8 months ago which is really bad from a security standpoint, vs https://hub.docker.com/r/armhf/debian/ which was updated 3 days ago.

This is not true today since official images on different architectures are updated simultaneously. For example https://hub.docker.com/r/arm32v5/debian/, https://hub.docker.com/r/arm32v7/debian/ and https://hub.docker.com/r/amd64/debian/ were all updated 9 days ago.

I hope that you will reconsider it. Stopping Pi Zero from running latest k8s is so disappointing.

@luxas

**Comment by kfox1111** [comment]
+1. some confusion has happened as the hub was rearranged and the older repos are still around. The newer ones do seem to be getting frequent updates.

**Comment by shinichi-hashitani** [comment]
Hi,

I am still in the middle of building k8s on ClusterHAT, but I was able to compile and build binaries for Pi Zero.

Basically, I have followed the below with some modifications:
https://povilasv.me/raspberrypi-kubelet/

I worked on wsl:
Linux DESKTOP-6GRDDIN 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux


#1 install gcc-arm-linux-gnueabi instead of gcc-arm-linux-gnueabihf
- sudo apt-get install gcc-arm-linux-gnueabihf
+ sudo apt-get install gcc-arm-linux-gnueabi

#2 before building for linux/arm, change two modifications to set_platform_envs() in hack/lib/golang.sh
# add GOARM
-  export GOOS=${platform%/*}
-  export GOARCH=${platform##*/}
+  export GOOS=${platform%/*}
+  export GOARCH=${platform##*/}
+  export GOARM=5
# change CC
-    case "${platform}" in
-      "linux/arm")
-        export CGO_ENABLED=1
-        export CC=arm-linux-gnueabihf-gcc
-        ;;
+    case "${platform}" in
+      "linux/arm")
+        export CGO_ENABLED=1
+        export CC=arm-linux-gnueabi-gcc
+        ;;

GOARM has to be 5. If you specify 6, you will get a linker error during the build. (Which I couldn't resolve.)

**Comment by wxdao** [comment]
@shinichi-hashitani It works for my Pi Zero! Thanks!

Also I resolved your problem on linker error. For Pi Zero, set GOARM=6 and keep gcc-arm-linux-gnueabihf. However for Pi 1 you gotta set GOARM=5 and use gcc-arm-linux-gnueabi instead.

**Comment by juliancheal** [comment]
@shinichi-hashitani this is great! I will give it a try thanks!

**Comment by dbwest** [comment]
Did you use `make all KUBE_BUILD_PLATFORMS=linux/arm` to build it?

**Comment by shinichi-hashitani** [comment]
@dbwest Yes, I used make all to build binaries. The exact commands I used were:
```
make all WHAT=cmd/kube-proxy KUBE_VERBOSE=5 KUBE_BUILD_PLATFORMS=linux/arm
make all WHAT=cmd/kubelet KUBE_VERBOSE=5 KUBE_BUILD_PLATFORMS=linux/arm
make all WHAT=cmd/kubectl KUBE_VERBOSE=5 KUBE_BUILD_PLATFORMS=linux/arm
```
I needed binaries for nodes, so only those three binaries were needed.

I didn't use kubeadm. I was following Kelsey Hightower's "Kubernetes the Hard Way". As described [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md), you just need to put those binaries in appropriate location.

**Comment by ammmze** [comment]
@shinichi-hashitani any idea what version of kubernetes you were building?

I haven't had any luck getting this to build for arm v6 (hoping to run on a pi zero w).

On versions `>= 1.12.0` I get something like this...

```
vendor/github.com/google/cadvisor/accelerators/nvidia.go:30:2: build constraints exclude all Go files in /private/var/folders/hn/gt2l8vq56vx9slvwry43xmz40000gn/T/tmp.A83ZihlF/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/mindprince/gonvml
!!! [0511 07:36:41] Call tree:
!!! [0511 07:36:41]  1: /private/var/folders/hn/gt2l8vq56vx9slvwry43xmz40000gn/T/tmp.A83ZihlF/hack/lib/golang.sh:601 kube::golang::build_some_binaries(...)
!!! [0511 07:36:41]  2: /private/var/folders/hn/gt2l8vq56vx9slvwry43xmz40000gn/T/tmp.A83ZihlF/hack/lib/golang.sh:736 kube::golang::build_binaries_for_platform(...)
!!! [0511 07:36:41]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! Error in /private/var/folders/hn/gt2l8vq56vx9slvwry43xmz40000gn/T/tmp.A83ZihlF/hack/lib/golang.sh:561
  Error in /private/var/folders/hn/gt2l8vq56vx9slvwry43xmz40000gn/T/tmp.A83ZihlF/hack/lib/golang.sh:561. 'go install "${build_args[@]}" "$@"' exited with status 1
```

And from `>= 1.10.0 & < 1.12.0` (`1.10.0` was the earliest i've tried so far), I get something like this...

```
F0511 07:39:30.480641   26683 openapi.go:116] Failed loading boilerplate: open /private/var/folders/hn/gt2l8vq56vx9slvwry43xmz40000gn/T/tmp.A83ZihlF/_output/local/go/src/k8s.io/gengo/boilerplate/boilerplate.go.txt: no such file or directory
!!! Error in ./hack/run-in-gopath.sh:33
  Error in ./hack/run-in-gopath.sh:33. '"${@}"' exited with status 255
Call stack:
  1: ./hack/run-in-gopath.sh:33 main(...)
Exiting with status 1
make[1]: *** [pkg/generated/openapi/zz_generated.openapi.go] Error 1
make: *** [generated_files] Error 2
```

**Comment by shinichi-hashitani** [comment]
@ammmze ,

Not exactly sure what is causing issues at your end, but the below is the details on my end:
Kubernetes - 1.10.2
Go - 19.4
I used WSL (Probably Ubuntu 16.x) for cross compiling those binaries.

Again, I followed the below with some modifications:
https://povilasv.me/raspberrypi-kubelet/
You can refer to this to confirm on the steps to go through.

I have prepared my note and exact steps I followed, but sorry that is only available in Japanese:
https://qiita.com/ShinHashitani/items/ea9ffdefce8ca5786da6

**Comment by pdkkid** [comment]
Any movement on adding back armel support for pi zero’s? I have quite a few laying around and would love to make a low cost/power cluster for demo purposes

**Comment by neolit123** [comment]
>Any movement on adding back armel support for pi zero’s? I have quite a few laying around and would love to make a low cost/power cluster for demo purposes

hi, as you can see in the discussion above, core Kubernetes dropped support for armv6l.
so i don't think there is a chance this support will be re-added.

if you want to use k8s / kubeadm on armv6l you must recompile everything (including CNI images).

**Comment by maxweisspoker** [comment]
I'm just chiming in to say that I have successfully compiled K8s 1.18.3 from source by compiling it in the golang:1.13-alpine docker image, which is a multi-arch image and includes a armv6. (I have Docker configred to use QEMU for emulation and can run containers for other architectures.)

By merely cloning the git repo, and following the 4-step make process on the readme page (i.e. just do make all WHAT=cmd/component), all k8s components except kubelet were statically compiled and run as standalone executables with no dependencies on my pi zero. (And if golang-alpine stops working, I can just bootstrap Arch Linux ARM from scratch, which should work fine for compiling.)

The only issue is that compiling kubelet still dynamically links to the system glibc library, and I haven't yet figured out how to fix that. I'm not a go programmer, and none of the compile flags I added for go of or gcc seemed to make a difference.  (Kubelet has some C code I guess, because it needs gcc to compile.)  I guess worst case I can bootstrap a docker image for every type of OS I run, so the glibc dynamic links will work, but I don't want to do that.

Debian still officially supports armel and has packages with a statically linked kubelet version, so my hacky solution currently is to just use their static binary from inside the armel deb package.

Lastly, you have to make your own repository with images that have these binaries (as well as the other versions), and configure kubeadm to pull those. And even more fun, although Docker runs on arm6, it incorrectly pulls arm7 images (a known bug for over 3 years), so you need to either change the arm7 image to just run the armel version, or make both arm6 and arm7 in the same image and just have the entry-point be a shell script that determines at runtime whether to launch the arm6 or arm7 program. Non-master nodes only need to run kubelet and kube-proxy, so those are probably the only images you need to do this for.

I'm actually just using ansible to setup k8s "the hard way", but I intend on still making compliant Docker images that can be drop-in replacements so kubeadm will work with them. If and when I can get kubelet to statically compile correctly, I will automate the process into a Dockerfile and stick the images on Docker Hub. Those images will have as many architectures as I can use, so ideally, we'll be able to use kubeadm on a multi-architecture cluster. E.g. amd64, arm64, arm6, and arm7.  I estimate that full production Docker and K8s on Pi Zero's (as worker nodes) still leaves at least 50mb-100mb ram left for running small images. And if I strip down the kernel, I can probably free up another 30 or 40 megs. But that's far in the future. If I can get a single static page being served by an nginx container managed by K8s on my Pi Zero, I'm calling that a win for the time being.

**Comment by aojea** [comment]
I have binaries for old raspberries models published here https://github.com/aojea/kubernetes-raspi-binaries
They are created with a github actions job, so feel free to reuse it
