### ISSUE TITLE
wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory 

### ISSUE THREAD

**Issue by pendeyao** [kubernetes/kubeadm#2535]
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests".
 This can take up to 4m0s [kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred: timed out waiting for the condition

This error is likely caused by:

The kubelet is not running
The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:

'systemctl status kubelet'
'journalctl -xeu kubelet'
Additionally, a control plane component may have crashed or exited when started by the container runtime. To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker. Here is one example how you may list all Kubernetes containers running in docker:

**Comment by pendeyao** [comment]
I solved it by upgrade the vm memory from 2G to 4G.

**Comment by pendeyao** [comment]
I solved it by upgrade the vm memory from 2G to 4G.

**Comment by neolit123** [comment]
probably the kube-apiserver failed to start.

2GB should be fine for a control-plane node, one could get with even less than that e.g. ~1.5GB.
but there are a lot of factors at play, if something is consuming all the memory on the machine there might not be enough for the  kube-apiserver. instead of the bump to 4GB it might be worth looking at kube-apiserver / kubelet logs and check for any errors.

kubeadm has some users on devices with constrained resources (Edge/IoT), so if they see performance regressions in the deployed components they will likely let us know right away..
