### ISSUE TITLE
Deploy control plane components using unix services

### ISSUE THREAD

**Issue by pparshin** [kubernetes/kubeadm#2579]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## What would you like to be added

I'd like to deploy the Kubernetes cluster as a managed solution where the end users have admin access to the cluster but the control plane is hidden.

Kubeadm uses static pods and Kubelet on the master nodes and registers them in the API Server. My proposal is adding the option to choose how to bootstrap the control plane components - using static pods or unix services. A way to deploy as unix services is described in the "Kubernetes The Hard Way". This method avoids using Kubelet and pods on the master nodes.

I have implemented the basic logic in the init, join and reset operations. If the community is interested I can push a PR draft and discuss it.

**Comment by neolit123** [comment]
What concerns do you have about the control plane mirror pods that the api server manages? Mirror pods do not give control to the kubeconfig administrator to the control plane and they are just for tracking of the static pods that the kubelet manages as a source.

'Kubeadm upgrade' is also essential to user workflows, not only init, join and reset.

Bigger proposals in k8s need a KEP https://github.com/kubernetes/enhancements/blob/master/keps/README.md
But first i would like to understand the need.

My initial reaction is to not accept such an enhancement because it will complicate the kubeadm maintenance and our team is very small and with limited bandwidth.

/kind feature
/priority awaiting-more-evidence

**Comment by pparshin** [comment]
The main concern is the security. Having the registered masters and running Kubelet allows scheduling the pod in the privileged mode and having access to the master node via nsenter. There might be other security issues which can affect the service SLA.

> My initial reaction is to not accept such an enhancement because it will complicate the kubeadm maintenance and our team is very small and with limited bandwidth.

Yes, I understand it. This issue has been created mostly to discuss the needing such functionality in Kubeadm.

**Comment by neolit123** [comment]
> The main concern is the security. Having the registered masters and running Kubelet allows scheduling the pod in the privileged mode and having access to the master node via nsenter. There might be other security issues which can affect the service SLA.

I don't think i see the attack vector with nsenter.
To gain access to a node with nsenter you'd have to run a privileged nsenter pod on that node?

If your concern is that the cp static pod containers are privileged with potential container escape, kubeadm 1.22 added an alpha feature called RootlessControlPlane.
https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2568-kubeadm-non-root-control-plane

It is also worth noting that the static pod approach is run in a number of deployments, inc openshift.

**Comment by pparshin** [comment]
> To gain access to a node with nsenter you'd have to run a privileged nsenter pod on that node?

Yes, I thought about this. Or user might run his pods on the master nodes which might affect them.

Anyway I got your point. It's not a common issue for kubeadm users so closing the feature request.
