### ISSUE TITLE
kubeadm cluster failed to restart control-plane after reboot

### ISSUE THREAD

**Issue by tamama** [kubernetes/kubeadm#2640]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):   1.23.2

**Environment**:
- **Kubernetes version** (use `kubectl version`):  1.23.2
- **Cloud provider or hardware configuration**:  Vagrant
- **OS** (e.g. from /etc/os-release):   CentOS/8
- **Kernel** (e.g. `uname -a`):   4.18.0-348.2.1.el8_5.x86_64
- **Container runtime (CRI)** (e.g. containerd, cri-o):   dockershim
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):    Flannel
- **Others**:

## What happened?

1. Reboot VM (3-nodes)
2. Control-plane containers did not start  (of course - since there is no systemd units)
3. Therefore, no API-server, controller-manager, etc.
4. Kubernetes cluster failed to restart after restart.

## What you expected to happen?

- Kubernetes cluster has to be recoverable after reboot.

## How to reproduce it (as minimally and precisely as possible)?

1. Setup a 3-node Kubernetes cluster on Vagrant - CentOS/8 via kubeadm
2. Reboot VM 
3. Observe that Kubernetes cluster does not start up, i.e. no api-server, nothing...

## Anything else we need to know?

I use Flannel as CNI provider.
It would be nice to have an official recommended CNI provider Kubernetes would suggest.

**Comment by neolit123** [comment]
kubeadm does not run as a service on the host, so if there is a failure it must one of the other services - container runtime, kubelet. this is out of control for kubeadm.

> I use Flannel as CNI provider.
> It would be nice to have an official recommended CNI provider Kubernetes would suggest.

kubeadm maintainers no longer recommend flannel due to some bugs in the past. you can try another CNI.
this issue might not be CNI, but Calico / Cillium / WeaveNet are known to work better.

> Observe that Kubernetes cluster does not start up, i.e. no api-server, nothing...

you must look at the logs of the kubelet.
it could also be a failure in the container runtime.

> Container runtime (CRI) (e.g. containerd, cri-o): dockershim

dockershim is  being removed.
https://kubernetes.io/blog/2020/12/02/dockershim-faq/
you can try containerd / CRI-O.

the support channels might have more ideas (see link from the bot below).
if you find a bug in the container runtime / kubelet, log an issue in kubernetes/kubernetes.

/support
