### ISSUE TITLE
Feature request: support flag "container-runtime-endpoint" and "image-service-endpoint" in kubeadm.

### ISSUE THREAD

**Issue by justadogistaken** [kubernetes/kubeadm#2642]
### Background
kubelet has supported the individual configuration for "container-runtime-endpoint" and "image-service-endpoint". However, only cri-socket supported in kubeadm. 
I hope to export these flags in kubeadm.

### Why is this needed?

Kubeadm lacks the flags of configuring image/runtime service in independently. 
That makes us have to reconfig the configuration of kubelet.

**Comment by neolit123** [comment]
i agree that this is a missing feature and that the CRI spec does have separate runtime and image service concepts.
but as you might understand the majority of kubeadm users don't need this.

the kubeadm `criSocket` concept is not ideal and kubeadm uses the flag / field to pass the `container-runtime-endpoint` flag to the kubelet and also pass `-r` flag to `crictl`.

here are a few questions for you:
- what is your use case exactly (why do you need this)?
- how are you setup-ing a separate image-service?
- what happens if the image service is not the same as the container runtime service and `ctrctl -r some-runtime-runtime-endpoint` is used for image pull instead of `ctrctl -i some-image-service-endpoint`?

**Comment by justadogistaken** [comment]
Thanks for your detailed reply.
### why do I need this?
In our scene, we developed an agent, which is between cri and kubelet. This agent has some specific logics on "ImagePull"(within image gRPC service, has been separated from runtime service). We found that kubelet provides the "runtime" and "image" service endpoint independently. So we're able to intercept "image" service only in our agent, which could lower the risk compares to intecept "image" & "runtime" service uniformly.

### how do I setup a separate image-service
Change the "image-service-endpoint" to our agent, and this agent will rely on concrete cri. But we will have some particular logics within some funcs, and invoke cri eventually.

### The third question
I may not get this problem. But I guess what backend behind `ctrctl` is not concerned with the configuration of `kubelet`?(especially kubelet has supported the separation already). What we hope to do is just make it possible to apply such configurations at `kubeadm` stage.

**Comment by neolit123** [comment]
> In our scene, we developed an agent, which is between cri and kubelet. This agent has some specific logics on "ImagePull"(within image gRPC service, has been separated from runtime service). We found that kubelet provides the "runtime" and "image" service endpoint independently. So we're able to intercept "image" service only in our agent, which could lower the risk compares to intecept "image" & "runtime" service uniformly.

ok, so you are trying to reduce security risks by introspective image pulls by the kubelet with your agent that implements the CRI ImageService?

> I may not get this problem. But I guess what backend behind ctrctl is not concerned with the configuration of kubelet?(especially kubelet has supported the separation already). What we hope to do is just make it possible to apply such configurations at kubeadm stage.

this is the question i'm the most interested in. the problem here is that kubeadm only uses `crictl -r (runtime-endpoint)` for image operations such as checking for existing images in the CR and pulling new ones. it does not support the specific image service endpoint.

to better illustrate my question: if i have my container runtime endpoint socket `foo`, and a custom image service endpoint `bar` would i still be able to pull images using `crictl -r` on the socket `foo`? my guess is, yes i could.
 
if image pull is only what your image cares about, you can add the `image-service-endpoint` flag in `{Init|Join}Configuration.nodeRegistration.kubeletExtraArgs` [link](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/). this would means that:
- all image pulls by the kubelet will go trough "image-service-endpoint"
- all pulls that kubeadm performs will go to the "container-runtime-endpoint"

if you consider kubeadm a trusted component the above should be fine for you, and you will still be able to use the agent on the kubelet pulls, but not on the kubeadm pulls.

**Comment by neolit123** [comment]
something else to note here is that kubeadm allows you to pass KubeletConfiguration [v1beta1](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) during `kubeadm init` that is shared with all nodes and configures the kubelets on them. unfortunately this configuration does not include the "container-runtime-endpoint" and "image-service-endpoint" options yet.

**Comment by justadogistaken** [comment]
> ok, so you are trying to reduce security risks by introspective image pulls by the kubelet with your agent that implements the CRI ImageService?

Sorry for my inaccurate description, we need "image-service-endpoint" is because we what the agent to intercept "image" only(we have our extra logics). And we fear to affect the "runtime" part, so we need "image-service-endpoint".

> if image pull is only what your agent cares about, you can add the image-service-endpoint flag in {Init|Join}Configuration.nodeRegistration.kubeletExtraArgs link and call init/join with this configuration accordingly. this would means that:

I guess `kubeletExtraArgs` could solve our problem.

Thank you very much. It's my bad, I didn't read throgh the doc. Sorry for wasting you time. And I appreciate it for your reply.

Let me just close the issue.

**Comment by neolit123** [comment]
> Thank you very much. It's my bad, I didn't read throgh the doc. Sorry for wasting you time. And I appreciate it for your reply.

no problem. this is not a waste of my time because i'm investigating the use case and if someone asks for the same in the future i can point them to this ticket.
