### ISSUE TITLE
kubeadm upgrade apply v1.26.0 throwing an error message

### ISSUE THREAD

**Issue by SamNandipaty** [kubernetes/kubeadm#2803]
could not retrieve API endpoints for node "xxxxxx" using pod annotations: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher

**Comment by neolit123** [comment]
/support

please check the links from the bot bellow.
thanks

**Comment by buccella** [comment]
For me, the problem was that kubeadm was failing to find the kube-apiserver pods; this was found after setting `--v=9`. 

This then opened the question as to why the apiserver pods were not being listed, even though the pod was running. The kubelet log on the relevant node revealed a "Failed creating a mirror pod" error about the kube-apiserver pod, due to an invalid value in the pod spec. Correcting this allowed the apiserver pods to be listed as expected, and the `kubeadm upgrade apply` command to succeed.
