### ISSUE TITLE
 Add flag "--skip-addons" to `kubeadm upgrade`

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubeadm#2846]
### What would you like to be added?

Add flag "--skip-addons" to `kubeadm upgrade`,  these addons upgrades will be skipped

### Why is this needed?

In some certain scenarios, cluster administrators want to skip addons(i.e. coredns,kube-proxy) upgrades. The addons upgrades may affect the data plane, so administrators must be more careful to upgrade these addons.

**Comment by neolit123** [comment]
kubeadm upgrade checks if the addon config maps are missing and then does not perform upgrade of the addons. but the FR here is different, perhaps in such a case admins should skip the addons on init and deploy them with custom names, so that they are not managed by kubeadm upgrade too.

i think ideally this skip should be possible with upgrade phases. we have a plan to add them but it's a complicated.

https://github.com/kubernetes/kubeadm/issues/1318

i am generally -1 to add this new flag, but let's see what other think.

**Comment by chenk008** [comment]
@neolit123 `kubeadm upgrade apply` support `--skip-phases` option, it looks good to me.

**Comment by neolit123** [comment]
ok, let's keep this planned for:
https://github.com/kubernetes/kubeadm/issues/1318
