### ISSUE TITLE
Feature Request - status command

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/kubeadm#304]
It would be nice to have a `kubeadm status` command that can be used to check if a host has been initialized already.

It seems the only way to do that right now is to run `kubeadm init` and let it fail in the pre-flight checks.

**Comment by pipejakob** [comment]
Do you have a usecase for doing this programmatically? Or is it just for human interactions, where you might be playing around and forget the state of a machine?

One thing you can do today is test the cluster health using `kubectl` instead of `kubeadm` (since `kubeadm` is only targeting initialization of master and nodes):

    $ kubectl get componentstatuses
    NAME                 STATUS    MESSAGE              ERROR
    controller-manager   Healthy   ok                   
    scheduler            Healthy   ok                   
    etcd-0               Healthy   {"health": "true"}   

This is what it looks like on host that hasn't been initialized:

    $ kubectl get componentstatuses
    The connection to the server localhost:8080 was refused - did you specify the right host or port?

This approach depends on having the `KUBECONFIG` environment variable set correctly and having proper permissions to the file before running `kubectl`, of course:

    $ sudo -s
    $ export KUBECONFIG=/etc/kubernetes/admin.conf

**Comment by gtirloni** [comment]
I was creating an Ansible playbook and at some point wanted to confirm that the host was 'clean' before proceeding with `kubeadm init`, just as a safety measure.

I think `kubectl get componentstatuses` could work in that case, thanks for the idea. For my use case, that should be enough.

**Comment by luxas** [comment]
Closing for now, we may want to revisit it at some point in the future, but I think for now `kubectl get cs` is good enough.

**Comment by LSmyrnaios** [comment]
Hi, could you please re-consider implementing this `kubeadm status` command?
Today if I use the suggested "kubectl get cs" I get this weird output:

```
NAME                 AGE
scheduler            <unknown>
controller-manager   <unknown>
etcd-0               <unknown>
```

**Comment by MaKaNu** [comment]
I have the same situation as @gtirloni, and I don't know if `kubectl get cs` is fitting the job. If I have fresh installation of kubernetes, the command returns connection refused.  At a first glance, this is ok, because we expect this and can trigger an ansible block command dependent. On the other hand, the  command results with rc=1, which is not a good behavior if I want the status of kubernetes. So I would need to apply antipatterns like ignore_errors. If I want to know the status of a system, an error should in no situation the result.
