### ISSUE TITLE
Cannot use config when invoking cert sa key phase alone

### ISSUE THREAD

**Issue by ttc0419** [kubernetes/kubeadm#3071]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.1", GitCommit:"6911225c3f747e1cd9d109c305436d08b668f086", GitTreeState:"archive", BuildDate:"2024-05-15T10:41:58Z", GoVersion:"go1.22.2", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?
```
[u@h k]# kubeadm init --config /tmp/cluster.yaml phase certs sa
unknown flag: --config

[u@h k]# cat /tmp/cluster.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
featureGates:
  PublicKeysECDSA: true
apiServer:
  certSANs: ['localhost', '127.0.0.1']
```

## What you expected to happen?
Generate ECDSA sa key pairs.

## How to reproduce it (as minimally and precisely as possible)?
Follow the commands above

## Anything else we need to know?
No

**Comment by neolit123** [comment]
how did you establish that it does not work?

```
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"30+", GitVersion:"v1.30.1-dirty", GitCommit:"6911225c3f747e1cd9d109c305436d08b668f086", GitTreeState:"dirty", BuildDate:"2024-06-06T17:13:32Z", GoVersion:"go1.22.2", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ cat kubeadmconfig.yaml
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
featureGates:
  PublicKeysECDSA: true
```

```
$ sudo openssl ec -in /etc/kubernetes/pki/ca.key -text 2>&1 | grep NIST
NIST CURVE: P-256
$ sudo openssl ec -in /etc/kubernetes/pki/sa.key -text 2>&1 | grep NIST
NIST CURVE: P-256
```

**Comment by ttc0419** [comment]
@neolit123 Because the sa key cert phase does not accept the config file, as in the "what happened" section: ```unknown flag: --config```.

**Comment by neolit123** [comment]
ok, that does seem like a minor problem.

to fix this this line:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/init/certs.go#L98

should be changed to:
`InheritFlags: getCertPhaseFlags("sa")`

but i think this should only be fixed in 1.31 and not backported to 1.30.

/help

**Comment by neolit123** [comment]
@ttc0419 your workaround for 1.30 and older versions is to call `kubeadm init phase certs all --config ...` and use the `sa.*` files
note that if certain certs exist kubeadm will not regenerate them. so if you are calling phase by phase you can do some clever edits / deletes of files.

... but more importantly we are removing the feature gate `PublicKeysECDSA` in the near future. that's because kubeadm v1beta4 will support `ClusterConfiguration.EncryptionAlgorithm` where you can use ECDSA.

**Comment by ttc0419** [comment]
@neolit123 BTW, is there a way to generate ECDSA keys in kubeconifg? They still use RSA regardless the feature gate.

**Comment by neolit123** [comment]
if so, that seems like a separate bug that we need to fix. i can't check the code right now.

**Comment by priyanshsao** [comment]
I'm new to open-source right now, @ttc0419 and @neolit123. Would you please help me in solving this issue ?
