### ISSUE TITLE
kubeadm init phase kubeconfig does not respect PublicKeysECDSA

### ISSUE THREAD

**Issue by ttc0419** [kubernetes/kubeadm#3072]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.0", GitCommit:"7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a", GitTreeState:"archive", BuildDate:"2024-06-05T13:36:39Z", GoVersion:"go1.22.4", Compiler:"gc", Platform:"linux/arm64"}
```

## What happened?
The ```client-key-data``` is a RSA key even ```PublicKeysECDSA``` feature gate is set to true.

## What you expected to happen?
The key should be a ECDSA key

## How to reproduce it (as minimally and precisely as possible)?
```
[root@lima-alpine ~]# cat << EOF > /tmp/cluster.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
featureGates:
  PublicKeysECDSA: true
apiServer:
  certSANs: ['localhost', '127.0.0.1']
EOF
[root@lima-alpine ~]# kubeadm init --config /tmp/cluster.yaml phase kubeconfig admin
[kubeconfig] Writing "admin.conf" kubeconfig file
```

## Anything else we need to know?
N/A

**Comment by neolit123** [comment]
i verified that the keys in kubeconfig files generated by kubeadm are indeed RSA.
thanks for testing this feature.

now i need to understand why this is happening.

**Comment by neolit123** [comment]
@ttc0419 

fix for 1.31 is here:
https://github.com/kubernetes/kubernetes/pull/125388

it seems we never tested kubeconfig files and the ECDSA feature gate never supported them.
there is no easy workaround for that from kubeadm so if you need ECDSA keys in kubeconfig files you'd have to manually generate them with openssl or something else.

i considered a backport for the PR fix to older releases, but it's kind of against the rules because we should not backport fixes for alpha features.

again, 1.31 will have v1beta4 which has the ClusterConfiguration.EncyrptionAlgorithm and the feature gate will be deprecated and removed with v1beta3.

**Comment by neolit123** [comment]
to avoid similar bugs in the future
https://github.com/kubernetes/kubeadm/issues/3073

**Comment by pacoxu** [comment]
It sounds like that this fg is not used.

Should we mention it in the document that this FG is alpha since 1.19 but is usable until 1.31?

**Comment by neolit123** [comment]
> > Should we mention it in the document that this FG is alpha since 1.19 but is usable until 1.31?
> 
> the bug only affects kubeconfig files. it works for other keys like ca.key. i can send a PR for k/website to mention this.

https://github.com/kubernetes/website/pull/46795
