### ISSUE TITLE
Add a --verbose flag to kubeadm init so we can see what is going on as each step is being executed

### ISSUE THREAD

**Issue by adriancuadrado** [kubernetes/kubeadm#3125]
### What would you like to be added?

A flag that would show the same output as --dry-run, but you see what is going on as the init command runs.

### Why is this needed?

This way we can tell more easily what exactly the command did, what was left to do and where it failed and why.

/sig cli

**Comment by neolit123** [comment]
the verbosity flag already exists and it's --v=x, try --v=10 for very detailed output about every client request and it's body.
we have no plans to add --verbose.

also, dry-run is a special mode that prints objects that "would have been used" that cannot be replicated in non-dry-run in a 1-to-1 fashion, since dry-run is a special mode.

**Comment by adriancuadrado** [comment]
@neolit123
> the verbosity flag already exists and it's --v=x, try --v=10 for very detailed output about every client request and its body.
> we have no plans to add --verbose.
> 
> also, dry-run is a special mode that prints objects that "would have been used" that cannot be replicated in non-dry-run in a 1-to-1 fashion, since dry-run is a special mode that is not equivalent to --v=10 with a real API client.
> 
> 

I assumed there wasn't any verbosity flag because I couldn't find it in the documentation: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

The verbosity flag you mentioned is not present in the above link. If it already exists then we have to include it there.

**Comment by neolit123** [comment]
the flag is global and comes from the parent `kubeadm` command. the same is true for `--rootfs`.

```
kubeadm --help

..

Flags:
      --add-dir-header   If true, adds the file directory to the header of the log messages
  -h, --help             help for kubeadm
      --rootfs string    The path to the 'real' host root filesystem. This will cause kubeadm to chroot into the provided path.
      --skip-headers     If true, avoid header prefixes in the log messages
  -v, --v Level          number for the log level verbosity
```

but that's a kubernetes/website problem, so you can log a ticket there.
we don't own the generator the produces the flags on the page you listed.
and i think the problem is somewhere here:
https://github.com/kubernetes-sigs/reference-docs/blob/ea17805ac787e3f012b704fe26d622fad3ced9ee/gen-compdocs/comps/gen_kube_docs.go#L62

**Comment by adriancuadrado** [comment]
Fun fact: After wasting more time than I probably should researching the biggest value used with `klog.V()`, I came to realize that if you want to be 100% sure to get as much verbosity as possible you must pass 99 to `-v` because that is the biggest number used, [right here](https://github.com/kubernetes/kubernetes/blob/475ee33f698334e5b00c58d3bef4083840ec12c5/staging/src/k8s.io/kubectl/pkg/cmd/util/helpers.go#L98) in kubectl. If you don't care about that one very specific log, 10 is enough because that's the second biggest value passed to `klog.V()` in the entire source code of kubernetes.
