### ISSUE TITLE
Add kubeadm CI jobs back to release-1.6-blocking

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#415]
The kubeadm CI jobs for 1.6 were [previously added](https://github.com/kubernetes/test-infra/pull/2375) to the `release-1.6-blocking` testgrid tab, but then [removed](https://github.com/kubernetes/test-infra/pull/3028) some time later as part of a sync with `releaselib.sh`.

This likely explains why no one noticed that all kubeadm 1.6 e2e jobs [stopped working](https://github.com/kubernetes/kubernetes/issues/51571) about a month ago when the bazel build started failing, and we likely released 1.6.9 with no signal about kubeadm's health.

I believe that we would still care if we released 1.6.10 with a broken version of kubeadm, so we should add these jobs back to the blocking list for 1.6 patch releases. I'm not sure if these tests were specifically removed or just part of the blast radius of an aggressive sync script.

Adding these tests back to the `-blocking` tab is still blocked on getting them back to green, of course, which is blocked on [fixing the bazel build](https://github.com/kubernetes/kubernetes/issues/51571).

@kubernetes/sig-cluster-lifecycle-bugs 
CC @david-mcmahon @enisoc

**Comment by enisoc** [comment]
We changed the way we use the `-blocking` versus `-all` release tabs in testgrid, but that's not what covered up the failing tests. I now look at `-all` which includes kubeadm, but the failure was obscured by https://github.com/kubernetes/test-infra/issues/4501.

The `-all` tab now serves the purpose that the `-blocking` tab used to -- a human looks at it and makes judgement calls about branch health. The new meaning of the `-blocking` tab is the set of tests that `anago` mechanically blocks on. The kubeadm test was never in this set.

@pipejakob I've been asked to cut v1.6.10 soon (Sep 13). Do you have any signal from manual testing on the release-1.6 branch since https://github.com/kubernetes/kubernetes/issues/51571 is still not resolved?

**Comment by pipejakob** [comment]
I haven't been manually testing 1.6 commits, but I would certainly volunteer to coordinate the testing needed to QA 1.6.10. I'll try to get some early testing done today or tomorrow to make sure we aren't already red, and then can repeat with a specific commit when you're close to selecting a candidate.

Thanks for the heads-up, and the explanation of the new meanings of the testgrid tabs.

**Comment by luxas** [comment]
@pipejakob https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#periodic-kubeadm-gce-1.6 is completely green. Thanks all!

(However, it isn't here: https://k8s-testgrid.appspot.com/release-1.6-blocking. If that's an issue, please reopen)
