### ISSUE TITLE
Kubeadm init version 

### ISSUE THREAD

**Issue by yongjianmu** [kubernetes/kubeadm#467]
## Versions

**kubeadm version** (use `kubeadm version`):
1.7.5

**Environment**:
- **Kubernetes version** (use `kubectl version`):
any

- **Cloud provider or hardware configuration**:
PC x86-64

- **OS** (e.g. from /etc/os-release):
CentOS Linux release 7.2.1511 (Core)
Ubuntu 16.04

- **Kernel** (e.g. `uname -a`):
3.10.0-327.22.2.el7.x86_64
4.4.0-22-generic

- **Others**:

## What happened?
The kubernetes version may differ from the version flag "--kubernetes-version"

## What you expected to happen?
The kubernetes version should be 1.7.6

## How to reproduce it (as minimally and precisely as possible)?
1.
yum install or apt-get install kubectl 1.7.0, kubelet 1.7.0
yum install or apt-get install kubeadm 1.7.5

2.
Use "kubeadm init --kubernetes-version=v1.7.6" to initial master, it could finish the process without error, but the kubernetes version number is still 1.7.0.

## Anything else we need to know?
Maybe it could be a feature improvement. Kubeadm could detect the local version and version flag "--kubernetes-version", and try to match the version flag by upgrading/downgrading local package or some other ways.

**Comment by pipejakob** [comment]
How are you checking the version of Kubernetes being installed, to see that it's different than your `--kubernetes-version` flag?

One of the things that I think is difficult to understand about the flow is that the name `--kubernetes-version` is a bit of a misnomer: it should really be called `--kubernetes-control-plane-version` or similar. After running `kubeadm init`, you shouldn't expect that the version of kubelet or kubectl should be different, but that the version of the Kubernetes control plane itself (apiserver, controller-manager, scheduler, etc.) is the correct version. You can see this by running `kubectl version` and looking at the Server version line.

If you're hoping to upgrade kubectl/kubelet, that's not something that kubeadm does, since there are so many different ways to install them in the first place. If you install these tools using `apt-get install`, then we expect you to do `apt-get update && apt-get upgrade` in order to upgrade them. Kubeadm just deals with initializing the control plane once you already have kubelet and a container runtime (like Docker) installed via other mechanisms.

Hope that helps.

**Comment by taherv** [comment]
@pipejakob Thanks for the clarification about what kubernetes-version really means.

A few questions : 

a. So it is implied here, that the version of kubelet running is "compatible" with the version of the control plane installed (which I chose by using the `--kubernetes-version` option) ? What happens when that compatibility breaks ? Isn't kubeadm just installing a broken cluster ? Or are there some hidden checks to ensure this doesn't happen ?

b. If my goal was to have a kubernetes cluster with ALL components (control plane, kubelet etc) from the exact same version, how would I achieve that using kubeadm ?

**Comment by taherv** [comment]
I think I have a response/workaround for my question (c).

During the "apt-get install kubeadm" step, I could install the correct versions of kubelet, kubectl **first** and then install kubeadm. That should do the trick !

**Comment by jamiehannaford** [comment]
@yongjianmu When you say "the kubernetes version number is still 1.7.0", what are you basing that on? Do you mean kubectl and kubelet are still 1.7.0, but the control panel is 1.7.6?

**Comment by yongjianmu** [comment]
Yes, the kubectl and kubelet version are still 1.7.0 when executing "kubeadm init  --kubernetes-version = 1.7.6". Like taherv mentioned above, is that mean kubelet is running in "compatible" mode? Not sure whether it is safe.

**Comment by jamiehannaford** [comment]
As @pipejakob already mentioned, I think `--kubernetes-version` is ambiguously named. It only refers to the version of the _control panel_ (apiserver, scheduler, controller-manager and addons), not the kubelet or kubeadm which are outside the control of kubeadm. It's recommended you upgrade these tools yourself using your method of choice.

**Comment by taherv** [comment]
I understand the current situation, and it is as you described @jamiehannaford .
But the unfortunate part is that "kubeadm" itself depends on "kubelet". So now the instructions are no longer accurate. Installing an arbitrary version of kubeadm might give you an arbitrary version of kubelet (since it installs its dependencies).

We need clear cut instructions (hopefully simple), that starts with the user's requirement of Kubernetes at a specific version, and ends with a cluster where ALL of kubernetes (including kubelet) are the same version.

We just wasted so much time in testing a 1.8 cluster, because we were missing **implementation** fixes in kubelet that were in 1.8, and kubeadm silently violated the "version" requirement.

**Comment by jamiehannaford** [comment]
@taherv @yongjianmu I've submitted a docs PR that hopefully makes this versioning contract a bit clearer (see https://github.com/kubernetes/kubernetes.github.io/pull/5815). I'm going to close this, but if you have any further questions, or feel more needs to be done, please comment and I'll reopen.
