### ISSUE TITLE
kubeadm master upgrade tests for 1.6 to 1.7 should work

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes/kubeadm#505]
Getting this to work is becoming a rabbit hole. This Issue is to keep track of the work.

Current status:
A. Need to backport test logic to 1.7 supporting kubernetes anywhere - https://github.com/kubernetes/kubernetes/pull/53996
B. To pass the kubeadm presubmit test, need to backport support for ci/someversion to kubeadm - https://github.com/kubernetes/kubernetes/pull/54173
C. To pass the kubeadm presubmit test, need to backport support etcd being pulled from the regular repositoring instread of the ci repository - need a PR to cherrypick at least https://github.com/kubernetes/kubernetes/commit/9a6ef9677a533b6c5dbe2fe8151ffc18dcb8857c

**Comment by jessicaochen** [comment]
@luxas @roberthbailey @pipejakob 
How important is it to us to have automated upgrade testing for kubeadm 1.6 -> 1.7? 

I have been working on it for a while and at this point the needed cherrypicking (See Issue description) is feeling like a rabbit hole (getting larger and larger as I discover more and more dependencies). At this point, I am starting to debate whether the support for the testing at that version is worth the risk taken with so much logic that needs to be backported.

**Comment by luxas** [comment]
So I think we definitely should have it (we have it), but it doesn't have to source the latest CI images. That feature didn't even exist in v1.7.

I'm fine with just using `--kubernetes-version latest` on v1.7, and `--kubernetes-version ci/latest` (which has more coverage) on v1.8.

IMO we should focus on v1.9 upgrade testing instead.

**Comment by jessicaochen** [comment]
@luxas - to clarify, it is the [presubmit's test use of ci/latest ](https://github.com/kubernetes/test-infra/commit/da87693ac20a3b99342d4bad7367a396dcde8710) that is blocking. The same presubmit runs against all pull requests so there is no concept of having different settings for different versions.

**Comment by pipejakob** [comment]
Ah, so it's not that our presubmit test is actually exercising the 1.6 -> 1.7 upgrade, but that we currently have the same presubmit job run both against the `master` and `release-1.7` branches, with the exact same configuration?

That feels broken to me, since the configuration of specifying `--kubernetes-version ci/latest` is really only expected to work on `master`. We shouldn't expect changes made to the `release-1.7` branch to be compatible with the latest CI build of the control plane, since that's going to be 1.9-alpha right now.

If we're also reusing the same presubmit test configuration against `release-1.8`, I would say that it's probably luck (and not expectation) that those tests are still passing when using `--kubernetes-version ci/latest`, and that is likely to break at some point during the 1.9 development cycle.

My suggestion is this:

1) Break apart our single presubmit into separate jobs based on the branch. Instead of every job being called `pull-kubernetes-e2e-kubeadm-gce`, we actually stick the name of the branch in the job name, like `pull-kubernetes-e2e-kubeadm-gce-master`.
2) Configure each job separately, so that `release-1.7` uses kubernetes-version `latest-1.7`, `release-1.8` uses `ci/latest-1.8` (or whatever the syntax is), and `master` uses `ci/latest`.
3) Update prow's config so that each test is only triggered on the correct branch, instead of reusing the same test against multiple branches.

@jessicaochen What do you think?

**Comment by fejta** [comment]
What is the point of `pull-kubernetes-e2e-kubeadm-gce`?
What does `--kubernetes-version ci/latest` test?

I am worried that neither `latest` and `ci/latest` test the code actually in the PR

**Comment by jessicaochen** [comment]
Synced with @fejta offline -

Options:
(A) The best/correct thing to do would be to somehow have kubeadm apply the version of kubernetes in the PR. Either push kuberentes somewhere and have kubeadm pull it down or somehow push it into the VMs and have kubeadm apply from local location.
(B) A somewhat close option is to apply the latest based on the version the PR is targeting.

Note that no matter which option we take to unblock the tests, we will eventually want (A) so that we are covering changes to the control plane that might break with kubeadm setup.
