### ISSUE TITLE
Feature: allow custom storage for etcd

### ISSUE THREAD

**Issue by tobad357** [kubernetes/kubeadm#544]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Currently when installing etcd via kubeadm local storage will always be used.
We would like a feature where we can pass in type of storage iscsi, ebs etc and the config for it
This way they kubelet on master can control the etcd storage instead of hacks where the storage has to be mounted first

## Versions

**kubeadm version** (use `kubeadm version`): 1.7.8

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.7.8
- **Cloud provider or hardware configuration**: Baremetal
- **OS** (e.g. from /etc/os-release): CentOS Linux 7.4
- **Kernel** (e.g. `uname -a`): 4.13.8-1.el7.elrepo.x86_64
- **Others**:

**Comment by luxas** [comment]
You can set up etcd externally to kubeadm. That is the other option we're giving you for further customization. You can also use the configuration file to customize a couple of parameters. Otherwise you can just rewrite `/etc/kubernetes/manifests/etcd.yaml` instead.

https://kubernetes.io/docs/reference/generated/kubeadm/
