### ISSUE TITLE
kubeadm upgrade only checks apiserver

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubeadm#645]
I manually upgraded my apiserver to 1.9.1, but I wanted to use kubeadm for the remainder of the upgrade (controller-manager, scheduler) but now that my API server is updated kubeadm believes I'm up to date.

**Comment by luxas** [comment]
Any suggestions on how we'd do that easily? Neither component serve `/version` (although I don't think it would be unreasonable to propose they'd start doing so), and ComponentStatuses (which we don't know if  we really can rely on anyway) doesn't include that information either. Of course we could parse the static Pod / DaemonSet manifest and extract the image tag in some fancy way from the image field, but I don't know if that'd be a good solution in the general case...

**Comment by brendandburns** [comment]
I feel like the image name is pretty good to use, the tag is created to follow semvar, so I think its pretty stable in general.

You can always print an error if it isn't the gcr image...

**Comment by kad** [comment]
Maybe be dependent on parsing imagenames is not the best way ? Maybe having switch for upgrade command that will allow "upgrade" to the same version as current one will be more user friendly ?

**Comment by sbezverk** [comment]
@luxas  I can look into it, since I have a bit of spare cycles, but i would like clarity on a solution. We can do "extended" check on upgrade, meaning when kubeadm upgrade is executed it checks all component for a matching version and upgrade those with mismatch, or a separate parameter of upgrade, something like "sync" which would go and do the same, sync all components to the one of API. Appreciate your feedback.

**Comment by timothysc** [comment]
Given that we have a well defined upgrade path, I'm closing this issue.
