### ISSUE TITLE
self-hosted upgrade is more complicated than needed.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubeadm#646]
Self-hosted upgrade appears to be more complicated than is necessary.

As far as I can tell, it creates a second daemonset (`temp`) and then uses this to swap things around.

However, I think the following approach is easier:
```
for each component in [apiserver, controller-manager, scheduler]:
   remove labels from pod <component>
   due to label removal daemonset creates a <new-instance-of-component>
   once <new-instance-of-component> pod exists (doesn't need to be running):
       delete pod <component>
```

**Comment by luxas** [comment]
> due to label removal daemonset creates a <new-instance-of-component>

Is the DaemonSet spec updated at this point or not? i.e. do you mean that `<new-instance-of-component>` is the upgraded component?

The other option we're considering is to fall back on static Pods during the single-master upgrade instead of self-hosting the temporary fallback component. We do this workaround solely because of the lack of an "first-add-then-delete" DaemonSet updateStrategy https://github.com/kubernetes/kubernetes/issues/48841

**Comment by kargakis** [comment]
@brendandburns's suggestion can work if you use the OnDelete strategy in the DaemonSet so an update to the DaemonSet podtemplate will not trigger a rollout. Then, you could update the DaemonSet, relabel the pod, and trigger the creation of an updated pod while the old one is still running.

**Comment by timothysc** [comment]
xref #651 - I'm going to put up a KEP soon to address these concerns and I'm going to close this issue and rally on a single self hosting issue that cross links.
