### ISSUE TITLE
kubeadm upgrade - etcd prepull image

### ISSUE THREAD

**Issue by GitBytes** [kubernetes/kubeadm#669]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?
kubeadm did not prepull the etcd docker image upon upgrade

This caused it to:
 * extend the etcd outage
 * kubeadm complains during upgrade
```
Error getting Pods with label selector "component=etcd"
``` 

## What you expected to happen?
Should have prepulled alongside `[kube-apiserver kube-controller-manager kube-scheduler]`

## How to reproduce it (as minimally and precisely as possible)?
`kubeadm upgrade apply v1.9.2`

## Anything else we need to know?
I started with version v1.8.3 and attempted to upgrade to v1.9.2 with kubeadm upgrade

**Comment by timothysc** [comment]
cc: @chuckha

**Comment by chuckha** [comment]
The upgrade path hardcodes a list of images to pull. One approach here is simply adding etcd to this list, but the problem with that is that kubeadm may end up pulling images unnecessarily (when etcd is external, kubeadm won't have any domain over that system).

A better approach would be to figure out which upgrades are being performed and pull the images based on the upgrades instead of a static list.

One thing I'm still thinking about are the assumptions being made by kubeadm upgrade. Does it always assume a colocated etcd?

**Comment by chuckha** [comment]
On further inspection I think adding Etcd to the list of master components is the right move since this 

https://kubernetes.io/docs/concepts/overview/components/ 

lists etcd as part of a master component.
