### ISSUE TITLE
v1alpha2 versioning for kubeadm configuration structs

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubeadm#750]
Presently, Kubeadm's config file is in alpha state, which means it can and [and does](https://github.com/kubernetes/kubeadm/issues/744) change without notice. Because Kubeadm needs to work consistently with configuration written by many versions, it's important that this format doesn't change.

The current configuration file [embeds TypeMeta](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go#L31), but this is never set. Even if it was, the alpha versions of some other structs we link to and embed mean we can't rely on this version being stable.

We want to get the Kubeadm MasterConfiguration version to at least v1beta1. This involves making sure all constituent structs are at least Beta status. We will also need to make sure the defaults and internal versions work with the Beta struct.

**Comment by timothysc** [comment]
I would definitely model this after the component-config work, and a KEP is required. 

This supersedes https://github.com/kubernetes/kubeadm/issues/117

**Comment by luxas** [comment]
The KEP https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0008-20180504-kubeadm-config-beta.md is not finished for actually reaching the beta state, needs to get updated with more information. Also, a couple of changes have been made to the proposal since @liztio was writing this.

However, we merged the inital kep as a starting point, and will improve it over time.
Here is a list of the changes that have been made to improve the kubeadm API machinery usage and APIs generally:
 - https://github.com/kubernetes/kubernetes/pull/63782
 - https://github.com/kubernetes/kubernetes/pull/63723
 - https://github.com/kubernetes/kubernetes/pull/63783
 - https://github.com/kubernetes/kubernetes/pull/63787
 - https://github.com/kubernetes/kubernetes/pull/63788
 - https://github.com/kubernetes/kubernetes/pull/63799
 - https://github.com/kubernetes/kubernetes/pull/63866
 - https://github.com/kubernetes/kubernetes/pull/63871
 - https://github.com/kubernetes/kubernetes/pull/63917
 - https://github.com/kubernetes/kubernetes/pull/64066
 - https://github.com/kubernetes/kubernetes/pull/64068
 - https://github.com/kubernetes/kubernetes/pull/64096
 - https://github.com/kubernetes/kubernetes/pull/64408

I repurposed this issue to be targeted at releasing the `v1alpha2` API version in time for kubeadm v1.11.
For beta, we need to
 - update the KEP to reflect the current state
 - improve the structure of our API types further ([gdocs proposal](https://docs.google.com/document/d/1Sk2VW7IKaLjrjf_4a1NEU0l7X0ysZoXq9lVBvH-ruYY/edit#heading=h.vd99op8cffst))
 - decide whether to embed other components' ComponentConfig in our types or not

The `v1alpha2` part here is done though, so I'm closing this issue, and opening a new one for `v1beta1`
