### ISSUE TITLE
Container Runtime Support: rkt

### ISSUE THREAD

**Issue by khaije1** [kubernetes/kubeadm#82]
This is a feature/documentation request.

Please abstract the container runtime checks/configuration so that they are either modular or can be bypassed. Also documentation to provide guidance on how to use alternate runtimes is helpful.

I'd like to use the rkt container runtime with kubeadm.

A flag or env-var could be used to communicate this intention, (ex.) `kubeadm --init --container-runtime=rkt`

Other options: ` --container-runtime=docker`, and ` --container-runtime=autodetect` 

The autodetect option could perform an ordered check for the existence of a container runtime, with docker being at the top of the list.

This would allow the feature to be included without breaking existing assumptions.

Cheers!

**Comment by pires** [comment]
There are a couple places where this change needs to happen:
1. Runtime `kubeadm` uses to bootstrap the cluster, e.g. start `kubelet`, and
2. Runtime used by the `kubelet` to run workloads.

The first seems to be the most complex at this point since `docker` is a dependency. But as soon as master components are self-hosted (WIP for 1.6) it should be trivial to run the `kubelet` with any supported container runtime or just download the binary and use as is.

The second only makes sense when CRI is GA. In the case of `rkt`, [rktlet](https://github.com/kubernetes-incubator/rktlet) is the obvious choice.

**Comment by luxas** [comment]
I think this is just a matter of customizing the systemd service that runs kubelet, right?

For me, using CRI is the long-term goal here and the real priority; I do not want to focus extra on docker, rkt or whatever, instead I just want what CRI is, a pluggable interface for kubelet to use.

**Comment by luxas** [comment]
How easy/hard is it to use rkt with kubelet? Just setting `--container-runtime=rkt`?
@kubernetes/sig-node-feature-requests

**Comment by luxas** [comment]
@khaije1 Would you be interested in providing a sample `.service` file for making kubelet use rkt instead of docker?

cc @aaronlevy @philips

**Comment by resouer** [comment]
@luxas You are right, CRI is always the first priority now.

Since we have CRI, using kubeadm with other CRI runtimes is super super easy, for example, hyper runtime: https://github.com/kubernetes/frakti/blob/master/docs/deploy.md

I really don't think it requires extra efforts or patches on kubeadm side.

**Comment by luxas** [comment]
@resouer No, no patches are needed on the kubeadm side, but I'd like more docs.

> https://github.com/kubernetes/frakti/blob/master/docs/deploy.md

Awesome guide you have there!! :boom:
Could you please update https://kubernetes.io/docs/admin/kubeadm/ to talk a little about how to enable rkt for example and reference that guide :smile:?

**Comment by resouer** [comment]
@luxas Yes, sure, I can add a sth like `use kubeadm with other CRI runtimes` part in the doc, please assign to me.

**Comment by luxas** [comment]
@resouer Thank you! Ping me on the PR and I'll review :+1:

**Comment by jamiehannaford** [comment]
@luxas Since https://github.com/kubernetes/kubernetes.github.io/pull/3941 is merged, can we close this?

**Comment by luxas** [comment]
@jamiehannaford Yes, I think so. If rkt folks want to document something specific to rkt, they can in the docs, but I think using CRI+rktlet will be fine for now. No changes needed to kubeadm at least
