### ISSUE TITLE
Cleanup config.NormalizeKubernetesVersion

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#902]
This function has a dependency hiding in the middle of it.

https://github.com/kubernetes/kubernetes/blob/63c90bb47ec99247cbf29542edfc443ffda7298b/cmd/kubeadm/app/util/config/masterconfig.go#L206

This makes a network call and should be injected as a dependency (behind an interface) so we can test the edge cases of this function.

**Comment by kad** [comment]
It is fine that function `kubeadmutil.KubernetesReleaseVersion()` makes network calls. it is expected to do that. However, for making tests for `NormalizeKubernetesVersion()` itself, we should be passing such  `MasterConfiguration` object that will have explicitly defined `KubernetesVersion` field. 
E.g. `v1.13.0` or `ci/v1.14.0-alpha.0.1166_0c7e207904edfd`
This will prevent network calls and will allow to test code paths inside `NormalizeKubernetesVersion()`

**Comment by timothysc** [comment]
please re-eval and see if this still applies.

**Comment by Klaven** [comment]
This is still an issue, will be submitting a PR in the future to correct.

**Comment by neolit123** [comment]
the unit test refactor related aspect of this ticket is resolved.
the version functions can now be tested.

however we have separate problems (no ticket yet) - random unit test fetch a version from the internet due to defaulting in the clusterconfiguration (a label is used).
this needs discussion.

/close
